In [65]:
import pandas as pd
import numpy as np

import sys
sys.path.append('../')

from sqlalchemy import create_engine, text

from config import RUTA_UNIDAD_ONE_DRIVE
from config import RUTA_LOCAL_ONE_DRIVE
from config import POSTGRES_UTEA

USER_DB = POSTGRES_UTEA['USER']
PASS_DB = POSTGRES_UTEA['PASSWORD']
HOST_DB = POSTGRES_UTEA['HOST']
PORT_DB = POSTGRES_UTEA['PORT']
NAME_DB = POSTGRES_UTEA['DATABASE']

ENGINE = create_engine(f'postgresql+psycopg://{USER_DB}:{PASS_DB}@{HOST_DB}:{PORT_DB}/{NAME_DB}')

In [66]:
#path_xlsx_avance = r'G:/Ingenio Azucarero Guabira S.A/UTEA - SEMANAL - AVANCE COSECHA/2024/AVANCE_SEMANAL/AVANCE DE COSECHA V1.xlsx'
path_xlsx_avance = r'G:\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - AVANCE COSECHA\2026\AVANCE SEMANAL\AVANCE DE COSECHA_V2.xlsx'
xlsx_resumen = pd.read_excel(path_xlsx_avance, sheet_name='AVANCE_FECHAS')
xlsx_resumen

            COD_COS                FECHA          AREA    ESTIMADO   ENTREGADO
0                 1  2026-08-08 00:00:00     29.700690     2116.08     2004.17
1                 1  2026-08-14 00:00:00     54.820913     2884.46     1982.15
2                 1  2026-08-26 00:00:00     36.761325     2013.00     1278.85
3                 1  2026-09-03 00:00:00     15.753562      943.64      789.60
4                 1  2026-09-09 00:00:00     33.054996     2664.80     2770.85
...             ...                  ...           ...         ...         ...
5389            672          (en blanco)      6.451635         NaN         NaN
5390    (en blanco)  2026-09-09 00:00:00           NaN         NaN      142.03
5391    (en blanco)  2026-09-16 00:00:00           NaN         NaN       72.11
5392    (en blanco)  2026-09-25 00:00:00           NaN         NaN       78.61
5393  Total general                  NaN  59002.118088  2355115.50  2193361.06

[5394 rows x 5 columns]

In [69]:
xlsx_resumen['COD_COS'] = pd.to_numeric(xlsx_resumen['COD_COS'], errors='coerce')
# Convertir a número (los no válidos se vuelven NaN)
xlsx_resumen['COD_COS'] = pd.to_numeric(xlsx_resumen['COD_COS'], errors='coerce')
# Eliminar filas con NaN
xlsx_resumen = xlsx_resumen.dropna(subset=['COD_COS'])
# Convertir a int
xlsx_resumen['COD_COS'] = xlsx_resumen['COD_COS'].astype(int)
xlsx_resumen

      COD_COS                FECHA       AREA  ESTIMADO  ENTREGADO
0           1  2026-08-08 00:00:00  29.700690   2116.08    2004.17
1           1  2026-08-14 00:00:00  54.820913   2884.46    1982.15
2           1  2026-08-26 00:00:00  36.761325   2013.00    1278.85
3           1  2026-09-03 00:00:00  15.753562    943.64     789.60
4           1  2026-09-09 00:00:00  33.054996   2664.80    2770.85
...       ...                  ...        ...       ...        ...
5385      670  2026-09-25 00:00:00        NaN       NaN      97.88
5386      670          (en blanco)  73.224410      0.00        NaN
5387      672  2026-08-26 00:00:00   1.347458       NaN      44.34
5388      672  2026-09-25 00:00:00   1.149286       NaN     126.56
5389      672          (en blanco)   6.451635       NaN        NaN

[5390 rows x 5 columns]

In [70]:
xlsx_resumen['ESTIMADO'].sum()

2355115.5

In [71]:
# 1. Intentar convertir a fecha (los no válidos quedan como NaT)
xlsx_resumen['FECHA'] = pd.to_datetime(xlsx_resumen['FECHA'], errors='coerce')
# Eliminar filas con fechas inválidas
xlsx_resumen = xlsx_resumen.dropna(subset=['FECHA'])

In [72]:
def colapsar_tabla(df_param):
    suma_acumulador = [None] * len(df_param)
    acumulador = 0
    contador = 0
    for i, r in df_param.iterrows():
        if(r['AREA'] == 0):
            acumulador += r['ENTREGADO']
            contador += 1
        else:
            acumulador += r['ENTREGADO']
            suma_acumulador[contador] = acumulador
            acumulador = 0
            contador += 1
            continue
    if suma_acumulador[-1] == None:
        suma_acumulador[-1] = acumulador

    df_param['ENTREGAS'] = suma_acumulador
    
    df_param = df_param.dropna(subset=['ENTREGAS'])
    df_param = df_param.drop(columns=['ENTREGADO'])
    #df_param = df_param[df_param['AREA']!=0]
    return df_param

In [73]:
list_cod_cos = list(set(xlsx_resumen['COD_COS']))

In [74]:
list_df = []

In [75]:
for i in list_cod_cos:
    grupo = xlsx_resumen[xlsx_resumen['COD_COS']==i].fillna(0)
    result = colapsar_tabla(grupo)
    list_df.append(result)

In [76]:
df_combinado = pd.concat(list_df, ignore_index=True)

In [77]:
df_combinado.to_excel(r'G:\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - AVANCE COSECHA\2026\AVANCE SEMANAL\_TEMP_AVANCE_FECHAS.xlsx', index=False, engine='openpyxl', sheet_name='data')
#df_combinado.to_excel('G:/Ingenio Azucarero Guabira S.A/UTEA - SEMANAL - AVANCE COSECHA/2024/AVANCE_SEMANAL/_TEMP_AVANCE_FECHAS.xlsx', index=False, engine='openpyxl', sheet_name='data')

In [78]:
df_combinado.head(2)

   COD_COS      FECHA       AREA  ESTIMADO  ENTREGAS
0        1 2026-08-08  29.700690   2116.08   2004.17
1        1 2026-08-14  54.820913   2884.46   1982.15

In [79]:
df_combinado['ENTREGAS'].sum()

2193068.31

In [80]:
def cargar_avance_fechas_a_db(df):
    df = df.rename(columns={
            'COD_COS': 'cod_cos',
            'FECHA': 'fecha',
            'AREA': 'area',
            'ESTIMADO': 'estimado',
            'ENTREGAS': 'entregas'
    })
    
    df['cod_cos']     = df['cod_cos'].astype('Int64')
    #df['fecha']   = pd.to_datetime(df["fecha"])
    df['area']  = df['area'].astype('float')
    df['estimado']   = df['estimado'].astype('float')
    df['entregas']   = df['entregas'].astype('float')

    #validad divicion entre 0
    df["tch_estimado"] = np.where(df["area"] > 0,
                              df["estimado"] / df["area"],
                              0)
    #validad divicion entre 0
    df["tch_entregas"] = np.where(df["area"] > 0,
                              df["entregas"] / df["area"],
                              0)
    
    df['diferencia_tn'] = df['entregas'] - df['estimado']
    df["porcen_dif"] = np.where(df["entregas"] > 0,
                              df["diferencia_tn"] / df["entregas"],
                              0)

    with ENGINE.begin() as conn:  # Inicia transacción
        # Vaciar la tabla y reiniciar secuencia
        conn.execute(text(f'TRUNCATE TABLE catastro_iag.data_avance_fechas RESTART IDENTITY'))
        
        # Insertar nuevos datos
        df.to_sql(
            name='data_avance_fechas',
            con=conn,  # conexión cruda dentro de la transacción
            schema='catastro_iag',
            if_exists='append',
            index=False,
            method='multi',
            chunksize=1000
        )
    print(f"✅ Se ha actualziado la tabla de codigos cosecha")

In [81]:
df_combinado

      COD_COS      FECHA       AREA  ESTIMADO  ENTREGAS
0           1 2026-08-08  29.700690   2116.08   2004.17
1           1 2026-08-14  54.820913   2884.46   1982.15
2           1 2026-08-26  36.761325   2013.00   1278.85
3           1 2026-09-03  15.753562    943.64    789.60
4           1 2026-09-09  33.054996   2664.80   2770.85
...       ...        ...        ...       ...       ...
3693      670 2026-06-20   5.668316    234.04    286.68
3694      670 2026-06-30   4.184842    228.38    284.41
3695      670 2026-09-25   0.000000      0.00    442.54
3696      672 2026-08-26   1.347458      0.00     44.34
3697      672 2026-09-25   1.149286      0.00    126.56

[3698 rows x 5 columns]

In [82]:
df_combinado.loc[(df_combinado['COD_COS'] == 30) & (df_combinado['FECHA'] == '2026-06-20'), 'ESTIMADO'] = -25000
df_combinado.loc[(df_combinado['COD_COS'] == 30) & (df_combinado['FECHA'] == '2026-07-07'), 'ESTIMADO'] = -5000
df_combinado.loc[(df_combinado['COD_COS'] == 30) & (df_combinado['FECHA'] == '2026-07-15'), 'ESTIMADO'] = 30000
df_combinado.loc[(df_combinado['COD_COS'] == 30) & (df_combinado['FECHA'] == '2026-07-30'), 'ESTIMADO'] = -30000
df_combinado.loc[(df_combinado['COD_COS'] == 30) & (df_combinado['FECHA'] == '2026-08-14'), 'ESTIMADO'] = -60000
df_combinado.loc[(df_combinado['COD_COS'] == 30) & (df_combinado['FECHA'] == '2026-08-29'), 'ESTIMADO'] = -18000

In [83]:
df_combinado[df_combinado['COD_COS'] == 30]

     COD_COS      FECHA        AREA  ESTIMADO  ENTREGAS
220       30 2026-05-29  112.378308   9087.45  11262.84
221       30 2026-06-05  103.696746   8196.55   7206.38
222       30 2026-06-20   24.759220 -25000.00   1588.18
223       30 2026-06-30   54.657204   4719.13   5408.70
224       30 2026-07-07  105.501008  -5000.00   6651.50
225       30 2026-07-15   27.347041  30000.00   7435.53
226       30 2026-07-22   90.815191   7912.90   3846.44
227       30 2026-07-30   50.662044 -30000.00   6384.11
228       30 2026-08-08   71.787848   5141.31   5123.58
229       30 2026-08-14   65.423072 -60000.00   5668.17
230       30 2026-08-26   70.857976   4897.64   5137.94
231       30 2026-08-29   14.200861 -18000.00     61.41
232       30 2026-09-25   16.864009   1121.51    898.38

In [84]:
cargar_avance_fechas_a_db(df_combinado)

✅ Se ha actualziado la tabla de codigos cosecha