In [130]:
import pandas as pd
import numpy as np

import sys
sys.path.append('../')

from sqlalchemy import create_engine, text

from config import RUTA_UNIDAD_ONE_DRIVE
from config import RUTA_LOCAL_ONE_DRIVE
from config import POSTGRES_UTEA

USER_DB = POSTGRES_UTEA['USER']
PASS_DB = POSTGRES_UTEA['PASSWORD']
HOST_DB = POSTGRES_UTEA['HOST']
PORT_DB = POSTGRES_UTEA['PORT']
NAME_DB = POSTGRES_UTEA['DATABASE']

ENGINE = create_engine(f'postgresql+psycopg://{USER_DB}:{PASS_DB}@{HOST_DB}:{PORT_DB}/{NAME_DB}')

In [131]:
#path_xlsx_avance = r'G:/Ingenio Azucarero Guabira S.A/UTEA - SEMANAL - AVANCE COSECHA/2024/AVANCE_SEMANAL/AVANCE DE COSECHA V1.xlsx'
path_xlsx_avance = r'G:\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - AVANCE COSECHA\2026\AVANCE SEMANAL\AVANCE DE COSECHA_V2.xlsx'
xlsx_resumen = pd.read_excel(path_xlsx_avance, sheet_name='AVANCE_FECHAS')
xlsx_resumen

            COD_COS                FECHA          AREA    ESTIMADO   ENTREGADO
0                 1  2026-06-05 00:00:00      1.560303        0.00         NaN
1                 1  2026-08-08 00:00:00     29.700690     2116.08     2004.17
2                 1  2026-08-14 00:00:00     54.820913     2884.46     1982.15
3                 1  2026-08-26 00:00:00     36.761325     2013.00     1278.85
4                 1  2026-09-03 00:00:00     15.753562      943.64      789.60
...             ...                  ...           ...         ...         ...
4354            670  2026-06-30 00:00:00      4.184842      228.38      284.41
4355            670          (en blanco)     73.224410        0.00         NaN
4356            672  2026-08-26 00:00:00      1.347458         NaN       44.34
4357            672          (en blanco)      7.600921         NaN         NaN
4358  Total general                  NaN  59147.635249  1854578.48  1758032.13

[4359 rows x 5 columns]

In [134]:
xlsx_resumen['COD_COS'] = pd.to_numeric(xlsx_resumen['COD_COS'], errors='coerce')
# Convertir a número (los no válidos se vuelven NaN)
xlsx_resumen['COD_COS'] = pd.to_numeric(xlsx_resumen['COD_COS'], errors='coerce')
# Eliminar filas con NaN
xlsx_resumen = xlsx_resumen.dropna(subset=['COD_COS'])
# Convertir a int
xlsx_resumen['COD_COS'] = xlsx_resumen['COD_COS'].astype(int)
xlsx_resumen

      COD_COS                FECHA       AREA  ESTIMADO  ENTREGADO
0           1  2026-06-05 00:00:00   1.560303      0.00        NaN
1           1  2026-08-08 00:00:00  29.700690   2116.08    2004.17
2           1  2026-08-14 00:00:00  54.820913   2884.46    1982.15
3           1  2026-08-26 00:00:00  36.761325   2013.00    1278.85
4           1  2026-09-03 00:00:00  15.753562    943.64     789.60
...       ...                  ...        ...       ...        ...
4353      670  2026-06-20 00:00:00   5.668316    234.04     286.68
4354      670  2026-06-30 00:00:00   4.184842    228.38     284.41
4355      670          (en blanco)  73.224410      0.00        NaN
4356      672  2026-08-26 00:00:00   1.347458       NaN      44.34
4357      672          (en blanco)   7.600921       NaN        NaN

[4358 rows x 5 columns]

In [135]:
xlsx_resumen['ESTIMADO'].sum()

1854578.48

In [136]:
# 1. Intentar convertir a fecha (los no válidos quedan como NaT)
xlsx_resumen['FECHA'] = pd.to_datetime(xlsx_resumen['FECHA'], errors='coerce')
# Eliminar filas con fechas inválidas
xlsx_resumen = xlsx_resumen.dropna(subset=['FECHA'])

In [137]:
def colapsar_tabla(df_param):
    suma_acumulador = [None] * len(df_param)
    acumulador = 0
    contador = 0
    for i, r in df_param.iterrows():
        if(r['AREA'] == 0):
            acumulador += r['ENTREGADO']
            contador += 1
        else:
            acumulador += r['ENTREGADO']
            suma_acumulador[contador] = acumulador
            acumulador = 0
            contador += 1
            continue
    if suma_acumulador[-1] == None:
        suma_acumulador[-1] = acumulador

    df_param['ENTREGAS'] = suma_acumulador
    
    df_param = df_param.dropna(subset=['ENTREGAS'])
    df_param = df_param.drop(columns=['ENTREGADO'])
    #df_param = df_param[df_param['AREA']!=0]
    return df_param

In [138]:
list_cod_cos = list(set(xlsx_resumen['COD_COS']))

In [139]:
list_df = []

In [140]:
for i in list_cod_cos:
    grupo = xlsx_resumen[xlsx_resumen['COD_COS']==i].fillna(0)
    result = colapsar_tabla(grupo)
    list_df.append(result)

In [141]:
df_combinado = pd.concat(list_df, ignore_index=True)

In [142]:
df_combinado.to_excel(r'G:\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - AVANCE COSECHA\2026\AVANCE SEMANAL\_TEMP_AVANCE_FECHAS.xlsx', index=False, engine='openpyxl', sheet_name='data')
#df_combinado.to_excel('G:/Ingenio Azucarero Guabira S.A/UTEA - SEMANAL - AVANCE COSECHA/2024/AVANCE_SEMANAL/_TEMP_AVANCE_FECHAS.xlsx', index=False, engine='openpyxl', sheet_name='data')

In [143]:
df_combinado.head(2)

   COD_COS      FECHA       AREA  ESTIMADO  ENTREGAS
0        1 2026-06-05   1.560303      0.00      0.00
1        1 2026-08-08  29.700690   2116.08   2004.17

In [144]:
df_combinado['ENTREGAS'].sum()

1758032.1300000001

In [145]:
def cargar_avance_fechas_a_db(df):
    df = df.rename(columns={
            'COD_COS': 'cod_cos',
            'FECHA': 'fecha',
            'AREA': 'area',
            'ESTIMADO': 'estimado',
            'ENTREGAS': 'entregas'
    })
    
    df['cod_cos']     = df['cod_cos'].astype('Int64')
    #df['fecha']   = pd.to_datetime(df["fecha"])
    df['area']  = df['area'].astype('float')
    df['estimado']   = df['estimado'].astype('float')
    df['entregas']   = df['entregas'].astype('float')

    #validad divicion entre 0
    df["tch_estimado"] = np.where(df["area"] > 0,
                              df["estimado"] / df["area"],
                              0)
    #validad divicion entre 0
    df["tch_entregas"] = np.where(df["area"] > 0,
                              df["entregas"] / df["area"],
                              0)
    
    df['diferencia_tn'] = df['entregas'] - df['estimado']
    df["porcen_dif"] = np.where(df["entregas"] > 0,
                              df["diferencia_tn"] / df["entregas"],
                              0)

    with ENGINE.begin() as conn:  # Inicia transacción
        # Vaciar la tabla y reiniciar secuencia
        conn.execute(text(f'TRUNCATE TABLE catastro_iag.data_avance_fechas RESTART IDENTITY'))
        
        # Insertar nuevos datos
        df.to_sql(
            name='data_avance_fechas',
            con=conn,  # conexión cruda dentro de la transacción
            schema='catastro_iag',
            if_exists='append',
            index=False,
            method='multi',
            chunksize=1000
        )
    print(f"✅ Se ha actualziado la tabla de codigos cosecha")

In [146]:
df_combinado

      COD_COS      FECHA       AREA  ESTIMADO  ENTREGAS
0           1 2026-06-05   1.560303      0.00      0.00
1           1 2026-08-08  29.700690   2116.08   2004.17
2           1 2026-08-14  54.820913   2884.46   1982.15
3           1 2026-08-26  36.761325   2013.00   1278.85
4           1 2026-09-03  15.753562    943.64    789.60
...       ...        ...        ...       ...       ...
3037      669 2026-06-30   5.598136    406.72      0.00
3038      669 2026-07-07  11.008677    741.84      0.00
3039      670 2026-06-20   5.668316    234.04    286.68
3040      670 2026-06-30   4.184842    228.38    284.41
3041      672 2026-08-26   1.347458      0.00     44.34

[3042 rows x 5 columns]

In [147]:
df_combinado.loc[(df_combinado['COD_COS'] == 30) & (df_combinado['FECHA'] == '2026-08-14'), 'ESTIMADO'] = -60000
df_combinado.loc[(df_combinado['COD_COS'] == 30) & (df_combinado['FECHA'] == '2026-07-15'), 'ESTIMADO'] = 30000
df_combinado.loc[(df_combinado['COD_COS'] == 30) & (df_combinado['FECHA'] == '2026-07-30'), 'ESTIMADO'] = -30000
df_combinado.loc[(df_combinado['COD_COS'] == 30) & (df_combinado['FECHA'] == '2026-06-20'), 'ESTIMADO'] = -25000

In [148]:
df_combinado[df_combinado['COD_COS'] == 30]

     COD_COS      FECHA        AREA  ESTIMADO  ENTREGAS
191       30 2026-05-29  112.378308   9087.45  11262.84
192       30 2026-06-05  103.696746   8196.55   7206.38
193       30 2026-06-20   24.759220 -25000.00   1588.18
194       30 2026-06-30   54.657204   4719.13   5408.70
195       30 2026-07-07  105.501008   9181.54   6651.50
196       30 2026-07-15   27.347041  30000.00   7435.53
197       30 2026-07-22   90.815191   7912.90   3846.44
198       30 2026-07-30   50.662044 -30000.00   6384.11
199       30 2026-08-08   71.787848   5141.31   5123.58
200       30 2026-08-14   65.423072 -60000.00   5668.17
201       30 2026-08-26   70.857976   4897.64   5137.94
202       30 2026-08-29   14.200861   1075.15     61.41

In [149]:
cargar_avance_fechas_a_db(df_combinado)

✅ Se ha actualziado la tabla de codigos cosecha