In [1]:
import sys
sys.path.append('../_amigocloud')

from sqlalchemy import create_engine, text
from amigocloud import AmigoCloud
from docx import Document
from docx2pdf import convert
import os
import json
import pandas as pd

# CONEXIÓN A GOOGLE DRIVE
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
import os

gauth = GoogleAuth()

# Si existe el archivo, intenta cargarlo
if os.path.exists("mycreds.txt"):
    gauth.LoadCredentialsFile("mycreds.txt")

# Si no hay credenciales o son inválidas, forzar nueva autenticación
if gauth.credentials is None or gauth.access_token_expired:
    try:
        gauth.LocalWebserverAuth()
    except:
        print("Error de autenticación. Eliminá 'mycreds.txt' y volvé a intentarlo.")
else:
    gauth.Authorize()

gauth.SaveCredentialsFile("mycreds.txt")
drive = GoogleDrive(gauth)

In [2]:
sys.path.append('..')

from config import RUTA_UNIDAD_ONE_DRIVE
from config import RUTA_LOCAL_ONE_DRIVE
from config import POSTGRES_UTEA
RUTA_COMPLETA = os.path.join(RUTA_UNIDAD_ONE_DRIVE, RUTA_LOCAL_ONE_DRIVE)

In [3]:
def get_ruta_informes():
    try:
        with open('../../ruta_informes.txt', 'r') as file:
            ruta_inf = file.readline().strip()
            return ruta_inf
    except FileNotFoundError:
        print("El archivo 'ruta_local.txt' no se encuentra en la ruta especificada.")
    return None

In [4]:
ruta_informes = get_ruta_informes()
directorio_origen = ruta_informes + r'\_informes'
directorio_destino = ruta_informes + r'\_pdf'

In [5]:
# Recorre y convierte a pdf archivos .docx que no empiezan con "_"
def convertir_docx_to_pdf():
    for archivo in os.listdir(directorio_origen):
        if archivo.lower().endswith(".docx") and not archivo.startswith("_"):
            ruta_docx = os.path.join(directorio_origen, archivo)
            ruta_pdf = os.path.join(directorio_destino, archivo.replace(".docx", ".pdf"))
            
            try:
                convert(ruta_docx, ruta_pdf)
                print(ruta_docx)
                if os.path.exists(ruta_pdf):
                    print(f"✅ Convertido: {archivo}")
                    os.remove(ruta_docx)
                    print(f"🗑️ Eliminado original: {archivo}")
                else:
                    print(f"❌ Error: PDF no generado para {archivo}")
            except Exception as e:
                print(f"⚠️ Error al convertir {archivo}: {e}")

def obtener_engine():
    return create_engine(
        f"postgresql+psycopg2://{POSTGRES_UTEA['USER']}:{POSTGRES_UTEA['PASSWORD']}@{POSTGRES_UTEA['HOST']}:{POSTGRES_UTEA['PORT']}/{POSTGRES_UTEA['DATABASE']}"
    )

def cargar_link_to_db(url, cite):
    engine = obtener_engine()
    try:
        with engine.begin() as conn:
            query = text("""
                UPDATE drones_control_bio.resumen_control_bio SET link = :url WHERE cite = :cite
            """)
            conn.execute(query, {"url": url, "cite": cite})
            print(f"✔️ Se registro link para CITE: {cite}" )
    except Exception as e:
        print(f"❌ Error al actualizar CITE: {cite}, {e}")

def get_registros_sin_enviar():
    engine = obtener_engine()
    try:
        query = """
            SELECT *
            FROM drones_control_bio.resumen_control_bio
            WHERE enviado = false
        """
        df = pd.read_sql(query, engine)
        return df
    except Exception as e:
        print(f"❌ Error al consultar unidades sin labor: {e}")
        return pd.DataFrame()
    return None

In [6]:
convertir_docx_to_pdf()

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\1.docx
✅ Convertido: 1.docx
🗑️ Eliminado original: 1.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\10.docx
✅ Convertido: 10.docx
🗑️ Eliminado original: 10.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\100.docx
✅ Convertido: 100.docx
🗑️ Eliminado original: 100.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\101.docx
✅ Convertido: 101.docx
🗑️ Eliminado original: 101.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\102.docx
✅ Convertido: 102.docx
🗑️ Eliminado original: 102.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\103.docx
✅ Convertido: 103.docx
🗑️ Eliminado original: 103.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\104.docx
✅ Convertido: 104.docx
🗑️ Eliminado original: 104.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\105.docx
✅ Convertido: 105.docx
🗑️ Eliminado original: 105.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\106.docx
✅ Convertido: 106.docx
🗑️ Eliminado original: 106.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\107.docx
✅ Convertido: 107.docx
🗑️ Eliminado original: 107.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\108.docx
✅ Convertido: 108.docx
🗑️ Eliminado original: 108.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\109.docx
✅ Convertido: 109.docx
🗑️ Eliminado original: 109.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\11.docx
✅ Convertido: 11.docx
🗑️ Eliminado original: 11.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\110.docx
✅ Convertido: 110.docx
🗑️ Eliminado original: 110.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\112.docx
✅ Convertido: 112.docx
🗑️ Eliminado original: 112.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\113.docx
✅ Convertido: 113.docx
🗑️ Eliminado original: 113.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\114.docx
✅ Convertido: 114.docx
🗑️ Eliminado original: 114.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\115.docx
✅ Convertido: 115.docx
🗑️ Eliminado original: 115.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\116.docx
✅ Convertido: 116.docx
🗑️ Eliminado original: 116.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\117.docx
✅ Convertido: 117.docx
🗑️ Eliminado original: 117.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\118.docx
✅ Convertido: 118.docx
🗑️ Eliminado original: 118.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\119.docx
✅ Convertido: 119.docx
🗑️ Eliminado original: 119.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\12.docx
✅ Convertido: 12.docx
🗑️ Eliminado original: 12.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\120.docx
✅ Convertido: 120.docx
🗑️ Eliminado original: 120.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\121.docx
✅ Convertido: 121.docx
🗑️ Eliminado original: 121.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\122.docx
✅ Convertido: 122.docx
🗑️ Eliminado original: 122.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\123.docx
✅ Convertido: 123.docx
🗑️ Eliminado original: 123.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\124.docx
✅ Convertido: 124.docx
🗑️ Eliminado original: 124.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\125.docx
✅ Convertido: 125.docx
🗑️ Eliminado original: 125.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\126.docx
✅ Convertido: 126.docx
🗑️ Eliminado original: 126.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\127.docx
✅ Convertido: 127.docx
🗑️ Eliminado original: 127.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\128.docx
✅ Convertido: 128.docx
🗑️ Eliminado original: 128.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\129.docx
✅ Convertido: 129.docx
🗑️ Eliminado original: 129.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\13.docx
✅ Convertido: 13.docx
🗑️ Eliminado original: 13.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\130.docx
✅ Convertido: 130.docx
🗑️ Eliminado original: 130.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\131.docx
✅ Convertido: 131.docx
🗑️ Eliminado original: 131.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\132.docx
✅ Convertido: 132.docx
🗑️ Eliminado original: 132.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\134.docx
✅ Convertido: 134.docx
🗑️ Eliminado original: 134.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\135.docx
✅ Convertido: 135.docx
🗑️ Eliminado original: 135.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\137.docx
✅ Convertido: 137.docx
🗑️ Eliminado original: 137.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\138.docx
✅ Convertido: 138.docx
🗑️ Eliminado original: 138.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\139.docx
✅ Convertido: 139.docx
🗑️ Eliminado original: 139.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\14.docx
✅ Convertido: 14.docx
🗑️ Eliminado original: 14.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\140.docx
✅ Convertido: 140.docx
🗑️ Eliminado original: 140.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\141.docx
✅ Convertido: 141.docx
🗑️ Eliminado original: 141.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\142.docx
✅ Convertido: 142.docx
🗑️ Eliminado original: 142.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\143.docx
✅ Convertido: 143.docx
🗑️ Eliminado original: 143.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\144.docx
✅ Convertido: 144.docx
🗑️ Eliminado original: 144.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\145.docx
✅ Convertido: 145.docx
🗑️ Eliminado original: 145.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\146.docx
✅ Convertido: 146.docx
🗑️ Eliminado original: 146.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\147.docx
✅ Convertido: 147.docx
🗑️ Eliminado original: 147.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\148.docx
✅ Convertido: 148.docx
🗑️ Eliminado original: 148.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\149.docx
✅ Convertido: 149.docx
🗑️ Eliminado original: 149.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\15.docx
✅ Convertido: 15.docx
🗑️ Eliminado original: 15.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\150.docx
✅ Convertido: 150.docx
🗑️ Eliminado original: 150.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\151.docx
✅ Convertido: 151.docx
🗑️ Eliminado original: 151.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\152.docx
✅ Convertido: 152.docx
🗑️ Eliminado original: 152.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\153.docx
✅ Convertido: 153.docx
🗑️ Eliminado original: 153.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\154.docx
✅ Convertido: 154.docx
🗑️ Eliminado original: 154.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\155.docx
✅ Convertido: 155.docx
🗑️ Eliminado original: 155.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\158.docx
✅ Convertido: 158.docx
🗑️ Eliminado original: 158.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\159.docx
✅ Convertido: 159.docx
🗑️ Eliminado original: 159.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\16.docx
✅ Convertido: 16.docx
🗑️ Eliminado original: 16.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\161.docx
✅ Convertido: 161.docx
🗑️ Eliminado original: 161.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\162.docx
✅ Convertido: 162.docx
🗑️ Eliminado original: 162.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\163.docx
✅ Convertido: 163.docx
🗑️ Eliminado original: 163.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\164.docx
✅ Convertido: 164.docx
🗑️ Eliminado original: 164.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\165.docx
✅ Convertido: 165.docx
🗑️ Eliminado original: 165.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\166.docx
✅ Convertido: 166.docx
🗑️ Eliminado original: 166.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\167.docx
✅ Convertido: 167.docx
🗑️ Eliminado original: 167.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\169.docx
✅ Convertido: 169.docx
🗑️ Eliminado original: 169.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\17.docx
✅ Convertido: 17.docx
🗑️ Eliminado original: 17.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\170.docx
✅ Convertido: 170.docx
🗑️ Eliminado original: 170.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\171.docx
✅ Convertido: 171.docx
🗑️ Eliminado original: 171.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\172.docx
✅ Convertido: 172.docx
🗑️ Eliminado original: 172.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\173.docx
✅ Convertido: 173.docx
🗑️ Eliminado original: 173.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\174.docx
✅ Convertido: 174.docx
🗑️ Eliminado original: 174.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\175.docx
✅ Convertido: 175.docx
🗑️ Eliminado original: 175.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\176.docx
✅ Convertido: 176.docx
🗑️ Eliminado original: 176.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\177.docx
✅ Convertido: 177.docx
🗑️ Eliminado original: 177.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\179.docx
✅ Convertido: 179.docx
🗑️ Eliminado original: 179.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\18.docx
✅ Convertido: 18.docx
🗑️ Eliminado original: 18.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\180.docx
✅ Convertido: 180.docx
🗑️ Eliminado original: 180.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\181.docx
✅ Convertido: 181.docx
🗑️ Eliminado original: 181.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\182.docx
✅ Convertido: 182.docx
🗑️ Eliminado original: 182.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\183.docx
✅ Convertido: 183.docx
🗑️ Eliminado original: 183.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\185.docx
✅ Convertido: 185.docx
🗑️ Eliminado original: 185.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\186.docx
✅ Convertido: 186.docx
🗑️ Eliminado original: 186.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\187.docx
✅ Convertido: 187.docx
🗑️ Eliminado original: 187.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\188.docx
✅ Convertido: 188.docx
🗑️ Eliminado original: 188.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\189.docx
✅ Convertido: 189.docx
🗑️ Eliminado original: 189.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\19.docx
✅ Convertido: 19.docx
🗑️ Eliminado original: 19.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\191.docx
✅ Convertido: 191.docx
🗑️ Eliminado original: 191.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\192.docx
✅ Convertido: 192.docx
🗑️ Eliminado original: 192.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\193.docx
✅ Convertido: 193.docx
🗑️ Eliminado original: 193.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\194.docx
✅ Convertido: 194.docx
🗑️ Eliminado original: 194.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\195.docx
✅ Convertido: 195.docx
🗑️ Eliminado original: 195.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\196.docx
✅ Convertido: 196.docx
🗑️ Eliminado original: 196.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\198.docx
✅ Convertido: 198.docx
🗑️ Eliminado original: 198.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\199.docx
✅ Convertido: 199.docx
🗑️ Eliminado original: 199.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\2.docx
✅ Convertido: 2.docx
🗑️ Eliminado original: 2.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\20.docx
✅ Convertido: 20.docx
🗑️ Eliminado original: 20.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\200.docx
✅ Convertido: 200.docx
🗑️ Eliminado original: 200.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\201.docx
✅ Convertido: 201.docx
🗑️ Eliminado original: 201.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\202.docx
✅ Convertido: 202.docx
🗑️ Eliminado original: 202.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\203.docx
✅ Convertido: 203.docx
🗑️ Eliminado original: 203.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\204.docx
✅ Convertido: 204.docx
🗑️ Eliminado original: 204.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\206.docx
✅ Convertido: 206.docx
🗑️ Eliminado original: 206.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\207.docx
✅ Convertido: 207.docx
🗑️ Eliminado original: 207.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\208.docx
✅ Convertido: 208.docx
🗑️ Eliminado original: 208.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\209.docx
✅ Convertido: 209.docx
🗑️ Eliminado original: 209.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\21.docx
✅ Convertido: 21.docx
🗑️ Eliminado original: 21.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\210.docx
✅ Convertido: 210.docx
🗑️ Eliminado original: 210.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\211.docx
✅ Convertido: 211.docx
🗑️ Eliminado original: 211.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\212.docx
✅ Convertido: 212.docx
🗑️ Eliminado original: 212.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\213.docx
✅ Convertido: 213.docx
🗑️ Eliminado original: 213.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\214.docx
✅ Convertido: 214.docx
🗑️ Eliminado original: 214.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\215.docx
✅ Convertido: 215.docx
🗑️ Eliminado original: 215.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\216.docx
✅ Convertido: 216.docx
🗑️ Eliminado original: 216.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\218.docx
✅ Convertido: 218.docx
🗑️ Eliminado original: 218.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\219.docx
✅ Convertido: 219.docx
🗑️ Eliminado original: 219.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\22.docx
✅ Convertido: 22.docx
🗑️ Eliminado original: 22.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\220.docx
✅ Convertido: 220.docx
🗑️ Eliminado original: 220.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\221.docx
✅ Convertido: 221.docx
🗑️ Eliminado original: 221.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\222.docx
✅ Convertido: 222.docx
🗑️ Eliminado original: 222.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\223.docx
✅ Convertido: 223.docx
🗑️ Eliminado original: 223.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\224.docx
✅ Convertido: 224.docx
🗑️ Eliminado original: 224.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\225.docx
✅ Convertido: 225.docx
🗑️ Eliminado original: 225.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\226.docx
✅ Convertido: 226.docx
🗑️ Eliminado original: 226.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\227.docx
✅ Convertido: 227.docx
🗑️ Eliminado original: 227.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\228.docx
✅ Convertido: 228.docx
🗑️ Eliminado original: 228.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\229.docx
✅ Convertido: 229.docx
🗑️ Eliminado original: 229.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\23.docx
✅ Convertido: 23.docx
🗑️ Eliminado original: 23.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\230.docx
✅ Convertido: 230.docx
🗑️ Eliminado original: 230.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\231.docx
✅ Convertido: 231.docx
🗑️ Eliminado original: 231.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\232.docx
✅ Convertido: 232.docx
🗑️ Eliminado original: 232.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\233.docx
✅ Convertido: 233.docx
🗑️ Eliminado original: 233.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\234.docx
✅ Convertido: 234.docx
🗑️ Eliminado original: 234.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\235.docx
✅ Convertido: 235.docx
🗑️ Eliminado original: 235.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\236.docx
✅ Convertido: 236.docx
🗑️ Eliminado original: 236.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\237.docx
✅ Convertido: 237.docx
🗑️ Eliminado original: 237.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\238.docx
✅ Convertido: 238.docx
🗑️ Eliminado original: 238.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\24.docx
✅ Convertido: 24.docx
🗑️ Eliminado original: 24.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\240.docx
✅ Convertido: 240.docx
🗑️ Eliminado original: 240.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\241.docx
✅ Convertido: 241.docx
🗑️ Eliminado original: 241.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\242.docx
✅ Convertido: 242.docx
🗑️ Eliminado original: 242.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\243.docx
✅ Convertido: 243.docx
🗑️ Eliminado original: 243.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\244.docx
✅ Convertido: 244.docx
🗑️ Eliminado original: 244.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\245.docx
✅ Convertido: 245.docx
🗑️ Eliminado original: 245.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\247.docx
✅ Convertido: 247.docx
🗑️ Eliminado original: 247.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\248.docx
✅ Convertido: 248.docx
🗑️ Eliminado original: 248.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\249.docx
✅ Convertido: 249.docx
🗑️ Eliminado original: 249.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\25.docx
✅ Convertido: 25.docx
🗑️ Eliminado original: 25.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\250.docx
✅ Convertido: 250.docx
🗑️ Eliminado original: 250.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\251.docx
✅ Convertido: 251.docx
🗑️ Eliminado original: 251.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\252.docx
✅ Convertido: 252.docx
🗑️ Eliminado original: 252.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\253.docx
✅ Convertido: 253.docx
🗑️ Eliminado original: 253.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\254.docx
✅ Convertido: 254.docx
🗑️ Eliminado original: 254.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\255.docx
✅ Convertido: 255.docx
🗑️ Eliminado original: 255.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\256.docx
✅ Convertido: 256.docx
🗑️ Eliminado original: 256.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\257.docx
✅ Convertido: 257.docx
🗑️ Eliminado original: 257.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\258.docx
✅ Convertido: 258.docx
🗑️ Eliminado original: 258.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\259.docx
✅ Convertido: 259.docx
🗑️ Eliminado original: 259.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\26.docx
✅ Convertido: 26.docx
🗑️ Eliminado original: 26.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\260.docx
✅ Convertido: 260.docx
🗑️ Eliminado original: 260.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\262.docx
✅ Convertido: 262.docx
🗑️ Eliminado original: 262.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\264.docx
✅ Convertido: 264.docx
🗑️ Eliminado original: 264.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\265.docx
✅ Convertido: 265.docx
🗑️ Eliminado original: 265.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\266.docx
✅ Convertido: 266.docx
🗑️ Eliminado original: 266.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\267.docx
✅ Convertido: 267.docx
🗑️ Eliminado original: 267.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\268.docx
✅ Convertido: 268.docx
🗑️ Eliminado original: 268.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\269.docx
✅ Convertido: 269.docx
🗑️ Eliminado original: 269.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\270.docx
✅ Convertido: 270.docx
🗑️ Eliminado original: 270.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\271.docx
✅ Convertido: 271.docx
🗑️ Eliminado original: 271.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\272.docx
✅ Convertido: 272.docx
🗑️ Eliminado original: 272.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\273.docx
✅ Convertido: 273.docx
🗑️ Eliminado original: 273.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\274.docx
✅ Convertido: 274.docx
🗑️ Eliminado original: 274.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\275.docx
✅ Convertido: 275.docx
🗑️ Eliminado original: 275.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\276.docx
✅ Convertido: 276.docx
🗑️ Eliminado original: 276.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\277.docx
✅ Convertido: 277.docx
🗑️ Eliminado original: 277.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\278.docx
✅ Convertido: 278.docx
🗑️ Eliminado original: 278.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\279.docx
✅ Convertido: 279.docx
🗑️ Eliminado original: 279.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\28.docx
✅ Convertido: 28.docx
🗑️ Eliminado original: 28.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\280.docx
✅ Convertido: 280.docx
🗑️ Eliminado original: 280.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\281.docx
✅ Convertido: 281.docx
🗑️ Eliminado original: 281.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\282.docx
✅ Convertido: 282.docx
🗑️ Eliminado original: 282.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\283.docx
✅ Convertido: 283.docx
🗑️ Eliminado original: 283.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\284.docx
✅ Convertido: 284.docx
🗑️ Eliminado original: 284.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\285.docx
✅ Convertido: 285.docx
🗑️ Eliminado original: 285.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\286.docx
✅ Convertido: 286.docx
🗑️ Eliminado original: 286.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\287.docx
✅ Convertido: 287.docx
🗑️ Eliminado original: 287.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\288.docx
✅ Convertido: 288.docx
🗑️ Eliminado original: 288.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\289.docx
✅ Convertido: 289.docx
🗑️ Eliminado original: 289.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\29.docx
✅ Convertido: 29.docx
🗑️ Eliminado original: 29.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\290.docx
✅ Convertido: 290.docx
🗑️ Eliminado original: 290.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\291.docx
✅ Convertido: 291.docx
🗑️ Eliminado original: 291.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\292.docx
✅ Convertido: 292.docx
🗑️ Eliminado original: 292.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\293.docx
✅ Convertido: 293.docx
🗑️ Eliminado original: 293.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\294.docx
✅ Convertido: 294.docx
🗑️ Eliminado original: 294.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\295.docx
✅ Convertido: 295.docx
🗑️ Eliminado original: 295.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\296.docx
✅ Convertido: 296.docx
🗑️ Eliminado original: 296.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\297.docx
✅ Convertido: 297.docx
🗑️ Eliminado original: 297.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\298.docx
✅ Convertido: 298.docx
🗑️ Eliminado original: 298.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\299.docx
✅ Convertido: 299.docx
🗑️ Eliminado original: 299.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\3.docx
✅ Convertido: 3.docx
🗑️ Eliminado original: 3.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\30.docx
✅ Convertido: 30.docx
🗑️ Eliminado original: 30.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\300.docx
✅ Convertido: 300.docx
🗑️ Eliminado original: 300.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\301.docx
✅ Convertido: 301.docx
🗑️ Eliminado original: 301.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\302.docx
✅ Convertido: 302.docx
🗑️ Eliminado original: 302.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\303.docx
✅ Convertido: 303.docx
🗑️ Eliminado original: 303.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\304.docx
✅ Convertido: 304.docx
🗑️ Eliminado original: 304.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\305.docx
✅ Convertido: 305.docx
🗑️ Eliminado original: 305.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\306.docx
✅ Convertido: 306.docx
🗑️ Eliminado original: 306.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\307.docx
✅ Convertido: 307.docx
🗑️ Eliminado original: 307.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\308.docx
✅ Convertido: 308.docx
🗑️ Eliminado original: 308.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\309.docx
✅ Convertido: 309.docx
🗑️ Eliminado original: 309.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\31.docx
✅ Convertido: 31.docx
🗑️ Eliminado original: 31.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\310.docx
✅ Convertido: 310.docx
🗑️ Eliminado original: 310.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\311.docx
✅ Convertido: 311.docx
🗑️ Eliminado original: 311.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\312.docx
✅ Convertido: 312.docx
🗑️ Eliminado original: 312.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\313.docx
✅ Convertido: 313.docx
🗑️ Eliminado original: 313.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\314.docx
✅ Convertido: 314.docx
🗑️ Eliminado original: 314.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\315.docx
✅ Convertido: 315.docx
🗑️ Eliminado original: 315.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\316.docx
✅ Convertido: 316.docx
🗑️ Eliminado original: 316.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\317.docx
✅ Convertido: 317.docx
🗑️ Eliminado original: 317.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\318.docx
✅ Convertido: 318.docx
🗑️ Eliminado original: 318.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\319.docx
✅ Convertido: 319.docx
🗑️ Eliminado original: 319.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\32.docx
✅ Convertido: 32.docx
🗑️ Eliminado original: 32.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\320.docx
✅ Convertido: 320.docx
🗑️ Eliminado original: 320.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\321.docx
✅ Convertido: 321.docx
🗑️ Eliminado original: 321.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\322.docx
✅ Convertido: 322.docx
🗑️ Eliminado original: 322.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\323.docx
✅ Convertido: 323.docx
🗑️ Eliminado original: 323.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\324.docx
✅ Convertido: 324.docx
🗑️ Eliminado original: 324.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\325.docx
✅ Convertido: 325.docx
🗑️ Eliminado original: 325.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\326.docx
✅ Convertido: 326.docx
🗑️ Eliminado original: 326.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\327.docx
✅ Convertido: 327.docx
🗑️ Eliminado original: 327.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\328.docx
✅ Convertido: 328.docx
🗑️ Eliminado original: 328.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\329.docx
✅ Convertido: 329.docx
🗑️ Eliminado original: 329.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\33.docx
✅ Convertido: 33.docx
🗑️ Eliminado original: 33.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\330.docx
✅ Convertido: 330.docx
🗑️ Eliminado original: 330.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\331.docx
✅ Convertido: 331.docx
🗑️ Eliminado original: 331.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\332.docx
✅ Convertido: 332.docx
🗑️ Eliminado original: 332.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\333.docx
✅ Convertido: 333.docx
🗑️ Eliminado original: 333.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\334.docx
✅ Convertido: 334.docx
🗑️ Eliminado original: 334.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\335.docx
✅ Convertido: 335.docx
🗑️ Eliminado original: 335.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\336.docx
✅ Convertido: 336.docx
🗑️ Eliminado original: 336.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\339.docx
✅ Convertido: 339.docx
🗑️ Eliminado original: 339.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\34.docx
✅ Convertido: 34.docx
🗑️ Eliminado original: 34.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\340.docx
✅ Convertido: 340.docx
🗑️ Eliminado original: 340.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\341.docx
✅ Convertido: 341.docx
🗑️ Eliminado original: 341.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\342.docx
✅ Convertido: 342.docx
🗑️ Eliminado original: 342.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\343.docx
✅ Convertido: 343.docx
🗑️ Eliminado original: 343.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\344.docx
✅ Convertido: 344.docx
🗑️ Eliminado original: 344.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\345.docx
✅ Convertido: 345.docx
🗑️ Eliminado original: 345.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\346.docx
✅ Convertido: 346.docx
🗑️ Eliminado original: 346.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\347.docx
✅ Convertido: 347.docx
🗑️ Eliminado original: 347.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\35.docx
✅ Convertido: 35.docx
🗑️ Eliminado original: 35.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\350.docx
✅ Convertido: 350.docx
🗑️ Eliminado original: 350.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\351.docx
✅ Convertido: 351.docx
🗑️ Eliminado original: 351.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\352.docx
✅ Convertido: 352.docx
🗑️ Eliminado original: 352.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\353.docx
✅ Convertido: 353.docx
🗑️ Eliminado original: 353.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\354.docx
✅ Convertido: 354.docx
🗑️ Eliminado original: 354.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\357.docx
✅ Convertido: 357.docx
🗑️ Eliminado original: 357.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\358.docx
✅ Convertido: 358.docx
🗑️ Eliminado original: 358.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\359.docx
✅ Convertido: 359.docx
🗑️ Eliminado original: 359.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\36.docx
✅ Convertido: 36.docx
🗑️ Eliminado original: 36.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\360.docx
✅ Convertido: 360.docx
🗑️ Eliminado original: 360.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\361.docx
✅ Convertido: 361.docx
🗑️ Eliminado original: 361.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\362.docx
✅ Convertido: 362.docx
🗑️ Eliminado original: 362.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\363.docx
✅ Convertido: 363.docx
🗑️ Eliminado original: 363.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\364.docx
✅ Convertido: 364.docx
🗑️ Eliminado original: 364.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\365.docx
✅ Convertido: 365.docx
🗑️ Eliminado original: 365.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\366.docx
✅ Convertido: 366.docx
🗑️ Eliminado original: 366.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\368.docx
✅ Convertido: 368.docx
🗑️ Eliminado original: 368.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\369.docx
✅ Convertido: 369.docx
🗑️ Eliminado original: 369.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\37.docx
✅ Convertido: 37.docx
🗑️ Eliminado original: 37.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\370.docx
✅ Convertido: 370.docx
🗑️ Eliminado original: 370.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\371.docx
✅ Convertido: 371.docx
🗑️ Eliminado original: 371.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\372.docx
✅ Convertido: 372.docx
🗑️ Eliminado original: 372.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\373.docx
✅ Convertido: 373.docx
🗑️ Eliminado original: 373.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\374.docx
✅ Convertido: 374.docx
🗑️ Eliminado original: 374.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\375.docx
✅ Convertido: 375.docx
🗑️ Eliminado original: 375.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\376.docx
✅ Convertido: 376.docx
🗑️ Eliminado original: 376.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\377.docx
✅ Convertido: 377.docx
🗑️ Eliminado original: 377.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\38.docx
✅ Convertido: 38.docx
🗑️ Eliminado original: 38.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\380.docx
✅ Convertido: 380.docx
🗑️ Eliminado original: 380.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\381.docx
✅ Convertido: 381.docx
🗑️ Eliminado original: 381.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\382.docx
✅ Convertido: 382.docx
🗑️ Eliminado original: 382.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\384.docx
✅ Convertido: 384.docx
🗑️ Eliminado original: 384.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\385.docx
✅ Convertido: 385.docx
🗑️ Eliminado original: 385.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\386.docx
✅ Convertido: 386.docx
🗑️ Eliminado original: 386.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\387.docx
✅ Convertido: 387.docx
🗑️ Eliminado original: 387.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\388.docx
✅ Convertido: 388.docx
🗑️ Eliminado original: 388.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\389.docx
✅ Convertido: 389.docx
🗑️ Eliminado original: 389.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\39.docx
✅ Convertido: 39.docx
🗑️ Eliminado original: 39.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\390.docx
✅ Convertido: 390.docx
🗑️ Eliminado original: 390.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\391.docx
✅ Convertido: 391.docx
🗑️ Eliminado original: 391.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\392.docx
✅ Convertido: 392.docx
🗑️ Eliminado original: 392.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\393.docx
✅ Convertido: 393.docx
🗑️ Eliminado original: 393.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\394.docx
✅ Convertido: 394.docx
🗑️ Eliminado original: 394.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\395.docx
✅ Convertido: 395.docx
🗑️ Eliminado original: 395.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\396.docx
✅ Convertido: 396.docx
🗑️ Eliminado original: 396.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\398.docx
✅ Convertido: 398.docx
🗑️ Eliminado original: 398.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\399.docx
✅ Convertido: 399.docx
🗑️ Eliminado original: 399.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\4.docx
✅ Convertido: 4.docx
🗑️ Eliminado original: 4.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\40.docx
✅ Convertido: 40.docx
🗑️ Eliminado original: 40.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\400.docx
✅ Convertido: 400.docx
🗑️ Eliminado original: 400.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\401.docx
✅ Convertido: 401.docx
🗑️ Eliminado original: 401.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\402.docx
✅ Convertido: 402.docx
🗑️ Eliminado original: 402.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\403.docx
✅ Convertido: 403.docx
🗑️ Eliminado original: 403.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\404.docx
✅ Convertido: 404.docx
🗑️ Eliminado original: 404.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\405.docx
✅ Convertido: 405.docx
🗑️ Eliminado original: 405.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\406.docx
✅ Convertido: 406.docx
🗑️ Eliminado original: 406.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\408.docx
✅ Convertido: 408.docx
🗑️ Eliminado original: 408.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\409.docx
✅ Convertido: 409.docx
🗑️ Eliminado original: 409.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\41.docx
✅ Convertido: 41.docx
🗑️ Eliminado original: 41.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\410.docx
✅ Convertido: 410.docx
🗑️ Eliminado original: 410.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\412.docx
✅ Convertido: 412.docx
🗑️ Eliminado original: 412.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\414.docx
✅ Convertido: 414.docx
🗑️ Eliminado original: 414.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\416.docx
✅ Convertido: 416.docx
🗑️ Eliminado original: 416.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\417.docx
✅ Convertido: 417.docx
🗑️ Eliminado original: 417.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\419.docx
✅ Convertido: 419.docx
🗑️ Eliminado original: 419.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\420.docx
✅ Convertido: 420.docx
🗑️ Eliminado original: 420.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\421.docx
✅ Convertido: 421.docx
🗑️ Eliminado original: 421.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\422.docx
✅ Convertido: 422.docx
🗑️ Eliminado original: 422.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\423.docx
✅ Convertido: 423.docx
🗑️ Eliminado original: 423.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\424.docx
✅ Convertido: 424.docx
🗑️ Eliminado original: 424.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\425.docx
✅ Convertido: 425.docx
🗑️ Eliminado original: 425.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\426.docx
✅ Convertido: 426.docx
🗑️ Eliminado original: 426.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\429.docx
✅ Convertido: 429.docx
🗑️ Eliminado original: 429.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\430.docx
✅ Convertido: 430.docx
🗑️ Eliminado original: 430.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\432.docx
✅ Convertido: 432.docx
🗑️ Eliminado original: 432.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\433.docx
✅ Convertido: 433.docx
🗑️ Eliminado original: 433.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\434.docx
✅ Convertido: 434.docx
🗑️ Eliminado original: 434.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\435.docx
✅ Convertido: 435.docx
🗑️ Eliminado original: 435.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\437.docx
✅ Convertido: 437.docx
🗑️ Eliminado original: 437.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\438.docx
✅ Convertido: 438.docx
🗑️ Eliminado original: 438.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\44.docx
✅ Convertido: 44.docx
🗑️ Eliminado original: 44.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\440.docx
✅ Convertido: 440.docx
🗑️ Eliminado original: 440.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\443.docx
✅ Convertido: 443.docx
🗑️ Eliminado original: 443.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\444.docx
✅ Convertido: 444.docx
🗑️ Eliminado original: 444.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\445.docx
✅ Convertido: 445.docx
🗑️ Eliminado original: 445.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\446.docx
✅ Convertido: 446.docx
🗑️ Eliminado original: 446.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\447.docx
✅ Convertido: 447.docx
🗑️ Eliminado original: 447.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\448.docx
✅ Convertido: 448.docx
🗑️ Eliminado original: 448.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\449.docx
✅ Convertido: 449.docx
🗑️ Eliminado original: 449.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\45.docx
✅ Convertido: 45.docx
🗑️ Eliminado original: 45.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\450.docx
✅ Convertido: 450.docx
🗑️ Eliminado original: 450.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\451.docx
✅ Convertido: 451.docx
🗑️ Eliminado original: 451.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\452.docx
✅ Convertido: 452.docx
🗑️ Eliminado original: 452.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\455.docx
✅ Convertido: 455.docx
🗑️ Eliminado original: 455.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\456.docx
✅ Convertido: 456.docx
🗑️ Eliminado original: 456.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\457.docx
✅ Convertido: 457.docx
🗑️ Eliminado original: 457.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\458.docx
✅ Convertido: 458.docx
🗑️ Eliminado original: 458.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\459.docx
✅ Convertido: 459.docx
🗑️ Eliminado original: 459.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\46.docx
✅ Convertido: 46.docx
🗑️ Eliminado original: 46.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\460.docx
✅ Convertido: 460.docx
🗑️ Eliminado original: 460.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\462.docx
✅ Convertido: 462.docx
🗑️ Eliminado original: 462.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\463.docx
✅ Convertido: 463.docx
🗑️ Eliminado original: 463.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\464.docx
✅ Convertido: 464.docx
🗑️ Eliminado original: 464.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\465.docx
✅ Convertido: 465.docx
🗑️ Eliminado original: 465.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\466.docx
✅ Convertido: 466.docx
🗑️ Eliminado original: 466.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\468.docx
✅ Convertido: 468.docx
🗑️ Eliminado original: 468.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\469.docx
✅ Convertido: 469.docx
🗑️ Eliminado original: 469.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\47.docx
✅ Convertido: 47.docx
🗑️ Eliminado original: 47.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\473.docx
✅ Convertido: 473.docx
🗑️ Eliminado original: 473.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\474.docx
✅ Convertido: 474.docx
🗑️ Eliminado original: 474.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\475.docx
✅ Convertido: 475.docx
🗑️ Eliminado original: 475.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\479.docx
✅ Convertido: 479.docx
🗑️ Eliminado original: 479.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\48.docx
✅ Convertido: 48.docx
🗑️ Eliminado original: 48.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\480.docx
✅ Convertido: 480.docx
🗑️ Eliminado original: 480.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\482.docx
✅ Convertido: 482.docx
🗑️ Eliminado original: 482.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\49.docx
✅ Convertido: 49.docx
🗑️ Eliminado original: 49.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\5.docx
✅ Convertido: 5.docx
🗑️ Eliminado original: 5.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\50.docx
✅ Convertido: 50.docx
🗑️ Eliminado original: 50.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\500.docx
✅ Convertido: 500.docx
🗑️ Eliminado original: 500.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\501.docx
✅ Convertido: 501.docx
🗑️ Eliminado original: 501.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\502.docx
✅ Convertido: 502.docx
🗑️ Eliminado original: 502.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\503.docx
✅ Convertido: 503.docx
🗑️ Eliminado original: 503.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\504.docx
✅ Convertido: 504.docx
🗑️ Eliminado original: 504.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\505.docx
✅ Convertido: 505.docx
🗑️ Eliminado original: 505.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\508.docx
✅ Convertido: 508.docx
🗑️ Eliminado original: 508.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\509.docx
✅ Convertido: 509.docx
🗑️ Eliminado original: 509.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\51.docx
✅ Convertido: 51.docx
🗑️ Eliminado original: 51.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\511.docx
✅ Convertido: 511.docx
🗑️ Eliminado original: 511.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\513.docx
✅ Convertido: 513.docx
🗑️ Eliminado original: 513.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\514.docx
✅ Convertido: 514.docx
🗑️ Eliminado original: 514.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\516.docx
✅ Convertido: 516.docx
🗑️ Eliminado original: 516.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\517.docx
✅ Convertido: 517.docx
🗑️ Eliminado original: 517.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\518.docx
✅ Convertido: 518.docx
🗑️ Eliminado original: 518.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\519.docx
✅ Convertido: 519.docx
🗑️ Eliminado original: 519.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\52.docx
✅ Convertido: 52.docx
🗑️ Eliminado original: 52.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\520.docx
✅ Convertido: 520.docx
🗑️ Eliminado original: 520.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\521.docx
✅ Convertido: 521.docx
🗑️ Eliminado original: 521.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\523.docx
✅ Convertido: 523.docx
🗑️ Eliminado original: 523.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\525.docx
✅ Convertido: 525.docx
🗑️ Eliminado original: 525.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\526.docx
✅ Convertido: 526.docx
🗑️ Eliminado original: 526.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\527.docx
✅ Convertido: 527.docx
🗑️ Eliminado original: 527.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\529.docx
✅ Convertido: 529.docx
🗑️ Eliminado original: 529.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\530.docx
✅ Convertido: 530.docx
🗑️ Eliminado original: 530.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\531.docx
✅ Convertido: 531.docx
🗑️ Eliminado original: 531.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\532.docx
✅ Convertido: 532.docx
🗑️ Eliminado original: 532.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\533.docx
✅ Convertido: 533.docx
🗑️ Eliminado original: 533.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\534.docx
✅ Convertido: 534.docx
🗑️ Eliminado original: 534.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\535.docx
✅ Convertido: 535.docx
🗑️ Eliminado original: 535.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\537.docx
✅ Convertido: 537.docx
🗑️ Eliminado original: 537.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\538.docx
✅ Convertido: 538.docx
🗑️ Eliminado original: 538.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\539.docx
✅ Convertido: 539.docx
🗑️ Eliminado original: 539.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\54.docx
✅ Convertido: 54.docx
🗑️ Eliminado original: 54.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\541.docx
✅ Convertido: 541.docx
🗑️ Eliminado original: 541.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\542.docx
✅ Convertido: 542.docx
🗑️ Eliminado original: 542.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\544.docx
✅ Convertido: 544.docx
🗑️ Eliminado original: 544.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\545.docx
✅ Convertido: 545.docx
🗑️ Eliminado original: 545.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\547.docx
✅ Convertido: 547.docx
🗑️ Eliminado original: 547.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\548.docx
✅ Convertido: 548.docx
🗑️ Eliminado original: 548.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\549.docx
✅ Convertido: 549.docx
🗑️ Eliminado original: 549.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\55.docx
✅ Convertido: 55.docx
🗑️ Eliminado original: 55.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\550.docx
✅ Convertido: 550.docx
🗑️ Eliminado original: 550.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\552.docx
✅ Convertido: 552.docx
🗑️ Eliminado original: 552.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\555.docx
✅ Convertido: 555.docx
🗑️ Eliminado original: 555.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\556.docx
✅ Convertido: 556.docx
🗑️ Eliminado original: 556.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\557.docx
✅ Convertido: 557.docx
🗑️ Eliminado original: 557.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\558.docx
✅ Convertido: 558.docx
🗑️ Eliminado original: 558.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\56.docx
✅ Convertido: 56.docx
🗑️ Eliminado original: 56.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\560.docx
✅ Convertido: 560.docx
🗑️ Eliminado original: 560.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\561.docx
✅ Convertido: 561.docx
🗑️ Eliminado original: 561.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\562.docx
✅ Convertido: 562.docx
🗑️ Eliminado original: 562.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\563.docx
✅ Convertido: 563.docx
🗑️ Eliminado original: 563.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\564.docx
✅ Convertido: 564.docx
🗑️ Eliminado original: 564.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\565.docx
✅ Convertido: 565.docx
🗑️ Eliminado original: 565.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\566.docx
✅ Convertido: 566.docx
🗑️ Eliminado original: 566.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\568.docx
✅ Convertido: 568.docx
🗑️ Eliminado original: 568.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\57.docx
✅ Convertido: 57.docx
🗑️ Eliminado original: 57.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\570.docx
✅ Convertido: 570.docx
🗑️ Eliminado original: 570.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\576.docx
✅ Convertido: 576.docx
🗑️ Eliminado original: 576.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\577.docx
✅ Convertido: 577.docx
🗑️ Eliminado original: 577.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\578.docx
✅ Convertido: 578.docx
🗑️ Eliminado original: 578.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\58.docx
✅ Convertido: 58.docx
🗑️ Eliminado original: 58.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\581.docx
✅ Convertido: 581.docx
🗑️ Eliminado original: 581.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\582.docx
✅ Convertido: 582.docx
🗑️ Eliminado original: 582.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\583.docx
✅ Convertido: 583.docx
🗑️ Eliminado original: 583.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\585.docx
✅ Convertido: 585.docx
🗑️ Eliminado original: 585.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\586.docx
✅ Convertido: 586.docx
🗑️ Eliminado original: 586.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\587.docx
✅ Convertido: 587.docx
🗑️ Eliminado original: 587.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\588.docx
✅ Convertido: 588.docx
🗑️ Eliminado original: 588.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\59.docx
✅ Convertido: 59.docx
🗑️ Eliminado original: 59.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\592.docx
✅ Convertido: 592.docx
🗑️ Eliminado original: 592.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\593.docx
✅ Convertido: 593.docx
🗑️ Eliminado original: 593.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\594.docx
✅ Convertido: 594.docx
🗑️ Eliminado original: 594.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\596.docx
✅ Convertido: 596.docx
🗑️ Eliminado original: 596.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\597.docx
✅ Convertido: 597.docx
🗑️ Eliminado original: 597.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\598.docx
✅ Convertido: 598.docx
🗑️ Eliminado original: 598.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\599.docx
✅ Convertido: 599.docx
🗑️ Eliminado original: 599.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\6.docx
✅ Convertido: 6.docx
🗑️ Eliminado original: 6.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\60.docx
✅ Convertido: 60.docx
🗑️ Eliminado original: 60.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\600.docx
✅ Convertido: 600.docx
🗑️ Eliminado original: 600.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\601.docx
✅ Convertido: 601.docx
🗑️ Eliminado original: 601.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\602.docx
✅ Convertido: 602.docx
🗑️ Eliminado original: 602.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\603.docx
✅ Convertido: 603.docx
🗑️ Eliminado original: 603.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\605.docx
✅ Convertido: 605.docx
🗑️ Eliminado original: 605.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\606.docx
✅ Convertido: 606.docx
🗑️ Eliminado original: 606.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\607.docx
✅ Convertido: 607.docx
🗑️ Eliminado original: 607.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\608.docx
✅ Convertido: 608.docx
🗑️ Eliminado original: 608.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\609.docx
✅ Convertido: 609.docx
🗑️ Eliminado original: 609.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\61.docx
✅ Convertido: 61.docx
🗑️ Eliminado original: 61.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\610.docx
✅ Convertido: 610.docx
🗑️ Eliminado original: 610.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\611.docx
✅ Convertido: 611.docx
🗑️ Eliminado original: 611.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\612.docx
✅ Convertido: 612.docx
🗑️ Eliminado original: 612.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\613.docx
✅ Convertido: 613.docx
🗑️ Eliminado original: 613.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\614.docx
✅ Convertido: 614.docx
🗑️ Eliminado original: 614.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\615.docx
✅ Convertido: 615.docx
🗑️ Eliminado original: 615.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\616.docx
✅ Convertido: 616.docx
🗑️ Eliminado original: 616.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\617.docx
✅ Convertido: 617.docx
🗑️ Eliminado original: 617.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\618.docx
✅ Convertido: 618.docx
🗑️ Eliminado original: 618.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\619.docx
✅ Convertido: 619.docx
🗑️ Eliminado original: 619.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\62.docx
✅ Convertido: 62.docx
🗑️ Eliminado original: 62.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\620.docx
✅ Convertido: 620.docx
🗑️ Eliminado original: 620.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\621.docx
✅ Convertido: 621.docx
🗑️ Eliminado original: 621.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\622.docx
✅ Convertido: 622.docx
🗑️ Eliminado original: 622.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\623.docx
✅ Convertido: 623.docx
🗑️ Eliminado original: 623.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\624.docx
✅ Convertido: 624.docx
🗑️ Eliminado original: 624.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\625.docx
✅ Convertido: 625.docx
🗑️ Eliminado original: 625.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\626.docx
✅ Convertido: 626.docx
🗑️ Eliminado original: 626.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\627.docx
✅ Convertido: 627.docx
🗑️ Eliminado original: 627.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\629.docx
✅ Convertido: 629.docx
🗑️ Eliminado original: 629.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\63.docx
✅ Convertido: 63.docx
🗑️ Eliminado original: 63.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\630.docx
✅ Convertido: 630.docx
🗑️ Eliminado original: 630.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\631.docx
✅ Convertido: 631.docx
🗑️ Eliminado original: 631.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\632.docx
✅ Convertido: 632.docx
🗑️ Eliminado original: 632.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\633.docx
✅ Convertido: 633.docx
🗑️ Eliminado original: 633.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\634.docx
✅ Convertido: 634.docx
🗑️ Eliminado original: 634.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\635.docx
✅ Convertido: 635.docx
🗑️ Eliminado original: 635.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\636.docx
✅ Convertido: 636.docx
🗑️ Eliminado original: 636.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\637.docx
✅ Convertido: 637.docx
🗑️ Eliminado original: 637.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\638.docx
✅ Convertido: 638.docx
🗑️ Eliminado original: 638.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\639.docx
✅ Convertido: 639.docx
🗑️ Eliminado original: 639.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\64.docx
✅ Convertido: 64.docx
🗑️ Eliminado original: 64.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\640.docx
✅ Convertido: 640.docx
🗑️ Eliminado original: 640.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\641.docx
✅ Convertido: 641.docx
🗑️ Eliminado original: 641.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\642.docx
✅ Convertido: 642.docx
🗑️ Eliminado original: 642.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\643.docx
✅ Convertido: 643.docx
🗑️ Eliminado original: 643.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\644.docx
✅ Convertido: 644.docx
🗑️ Eliminado original: 644.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\645.docx
✅ Convertido: 645.docx
🗑️ Eliminado original: 645.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\646.docx
✅ Convertido: 646.docx
🗑️ Eliminado original: 646.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\647.docx
✅ Convertido: 647.docx
🗑️ Eliminado original: 647.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\65.docx
✅ Convertido: 65.docx
🗑️ Eliminado original: 65.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\650.docx
✅ Convertido: 650.docx
🗑️ Eliminado original: 650.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\651.docx
✅ Convertido: 651.docx
🗑️ Eliminado original: 651.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\652.docx
✅ Convertido: 652.docx
🗑️ Eliminado original: 652.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\653.docx
✅ Convertido: 653.docx
🗑️ Eliminado original: 653.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\654.docx
✅ Convertido: 654.docx
🗑️ Eliminado original: 654.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\655.docx
✅ Convertido: 655.docx
🗑️ Eliminado original: 655.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\656.docx
✅ Convertido: 656.docx
🗑️ Eliminado original: 656.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\657.docx
✅ Convertido: 657.docx
🗑️ Eliminado original: 657.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\658.docx
✅ Convertido: 658.docx
🗑️ Eliminado original: 658.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\659.docx
✅ Convertido: 659.docx
🗑️ Eliminado original: 659.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\67.docx
✅ Convertido: 67.docx
🗑️ Eliminado original: 67.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\68.docx
✅ Convertido: 68.docx
🗑️ Eliminado original: 68.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\69.docx
✅ Convertido: 69.docx
🗑️ Eliminado original: 69.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\7.docx
✅ Convertido: 7.docx
🗑️ Eliminado original: 7.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\70.docx
✅ Convertido: 70.docx
🗑️ Eliminado original: 70.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\71.docx
✅ Convertido: 71.docx
🗑️ Eliminado original: 71.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\72.docx
✅ Convertido: 72.docx
🗑️ Eliminado original: 72.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\73.docx
✅ Convertido: 73.docx
🗑️ Eliminado original: 73.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\74.docx
✅ Convertido: 74.docx
🗑️ Eliminado original: 74.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\75.docx
✅ Convertido: 75.docx
🗑️ Eliminado original: 75.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\76.docx
✅ Convertido: 76.docx
🗑️ Eliminado original: 76.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\78.docx
✅ Convertido: 78.docx
🗑️ Eliminado original: 78.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\79.docx
✅ Convertido: 79.docx
🗑️ Eliminado original: 79.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\8.docx
✅ Convertido: 8.docx
🗑️ Eliminado original: 8.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\81.docx
✅ Convertido: 81.docx
🗑️ Eliminado original: 81.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\82.docx
✅ Convertido: 82.docx
🗑️ Eliminado original: 82.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\83.docx
✅ Convertido: 83.docx
🗑️ Eliminado original: 83.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\84.docx
✅ Convertido: 84.docx
🗑️ Eliminado original: 84.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\85.docx
✅ Convertido: 85.docx
🗑️ Eliminado original: 85.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\86.docx
✅ Convertido: 86.docx
🗑️ Eliminado original: 86.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\87.docx
✅ Convertido: 87.docx
🗑️ Eliminado original: 87.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\88.docx
✅ Convertido: 88.docx
🗑️ Eliminado original: 88.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\9.docx
✅ Convertido: 9.docx
🗑️ Eliminado original: 9.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\90.docx
✅ Convertido: 90.docx
🗑️ Eliminado original: 90.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\92.docx
✅ Convertido: 92.docx
🗑️ Eliminado original: 92.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\93.docx
✅ Convertido: 93.docx
🗑️ Eliminado original: 93.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\94.docx
✅ Convertido: 94.docx
🗑️ Eliminado original: 94.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\95.docx
✅ Convertido: 95.docx
🗑️ Eliminado original: 95.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\96.docx
✅ Convertido: 96.docx
🗑️ Eliminado original: 96.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\97.docx
✅ Convertido: 97.docx
🗑️ Eliminado original: 97.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\98.docx
✅ Convertido: 98.docx
🗑️ Eliminado original: 98.docx

  0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Usuario\Desktop\PROYECTOS\_informes\99.docx
✅ Convertido: 99.docx
🗑️ Eliminado original: 99.docx

In [7]:
def cargar_pdf_to_drive(id_drive, title_file, path_file):
    try:
        # 1. Buscar si ya existe un archivo con el mismo nombre en la misma carpeta
        query = f"'{id_drive}' in parents and title = '{title_file}' and trashed = false"
        file_list = drive.ListFile({'q': query}).GetList()

        if file_list:
            # Si ya existe, usamos el primero encontrado
            file = file_list[0]
            print(f"[INFO] El archivo '{title_file}' ya existe. Se reemplazará.")
        else:
            # Si no existe, creamos uno nuevo
            file = drive.CreateFile({
                "mimeType": "application/pdf",
                "parents": [{"kind": "drive#fileLink", "id": id_drive}]
            })
            file['title'] = title_file
            print(f"[INFO] El archivo '{title_file}' no existe. Se creará uno nuevo.")

        # 2. Reemplazar el contenido
        file.SetContentFile(path_file)
        file.Upload()

        # 3. Dar permisos públicos si es nuevo
        if not file_list:
            file.InsertPermission({
                'type': 'anyone',
                'value': 'anyone',
                'role': 'reader'
            })

        print(f"✅[OK] Archivo '{title_file}' subido exitosamente.")
        return file['alternateLink']

    except Exception as e:
        print(f"❌[ERROR] No se pudo subir el archivo '{title_file}': {e}")
        return False

In [17]:
contenido = os.listdir(directorio_destino)
print(len(contenido))
contenido

2

['1530_SLCB_30-04-2026_C.I.T.T.C.A._CB-2025-715.pdf',
 '42667_SLCB_24-04-2026_AGROPECUARIA PESO SRL_CB-2025-716.pdf']

In [18]:
for file in contenido:
    partes = file.split('_')
    
    cite = partes[-1].split('.')[0]
    sigla = partes[1]
    title_file = file
    id_drive = '1sEfhWGATb7tkKgr6gcknH3ZA_ed_hGTq'
    path_file = os.path.join(directorio_destino, file)
    print(cite)
    url_drive = cargar_pdf_to_drive(id_drive, title_file, path_file)
    if url_drive == False:
        continue
    cargar_link_to_db(url_drive, cite)
    if os.path.exists(path_file):
        os.remove(path_file)
        print("✅ Archivo eliminado.")
    else:
        print("⚠️ El archivo no existe.")

CB-2025-715
[INFO] El archivo '1530_SLCB_30-04-2026_C.I.T.T.C.A._CB-2025-715.pdf' no existe. Se creará uno nuevo.
✅[OK] Archivo '1530_SLCB_30-04-2026_C.I.T.T.C.A._CB-2025-715.pdf' subido exitosamente.
✔️ Se registro link para CITE: CB-2025-715
✅ Archivo eliminado.
CB-2025-716
[INFO] El archivo '42667_SLCB_24-04-2026_AGROPECUARIA PESO SRL_CB-2025-716.pdf' no existe. Se creará uno nuevo.
✅[OK] Archivo '42667_SLCB_24-04-2026_AGROPECUARIA PESO SRL_CB-2025-716.pdf' subido exitosamente.
✔️ Se registro link para CITE: CB-2025-716
✅ Archivo eliminado.

In [10]:
import psycopg2

In [11]:
def obtener_conexion():
    return psycopg2.connect(
        host='localhost', 
        port=5433, 
        database='utea', 
        user='postgres', 
        password='A123456*')
    
def insertar_mensaje_whatsapp(cod_canero, nombre_canero, numero_contac, mensaje, enviado=False, fecha_enviado=None):
    try:
        conexion = obtener_conexion()
        cursor = conexion.cursor()
        cursor.execute("""
            INSERT INTO notificaciones_wsp.msj_whatsapp (
                cod_canero, nombre_canero, numero_cel, mensaje, enviado, fecha_enviado, numero_contac
            ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        """, (cod_canero, nombre_canero, 0, mensaje, enviado, fecha_enviado, numero_contac))
        
        conexion.commit()
        cursor.close()
        print("Mensaje insertado correctamente.")
    except Exception as e:
        conexion.rollback()
        print("Error inesperado")
    return None

def marcar_resumen_lib_enviado(id_resumen):
    try:
        conexion = obtener_conexion()
        cursor = conexion.cursor()
        cursor.execute("""
            UPDATE drones_control_bio.resumen_control_bio
            SET enviado = true
            WHERE id = %s
        """, (id_resumen,))
        conexion.commit()
        cursor.close()
        print(f"Mensaje con id={id_resumen} marcado como enviado.")
    except Exception as e:
        conexion.rollback()
        print(f"Error inesperado: {e}")
    finally:
        if conexion:
            conexion.close()
    return None

In [12]:
PATH_XLSX_CONTAC=r'G:\\Ingenio Azucarero Guabira S.A\\UTEA - SEMANAL - EQUIPO AVIACION UTEA\\Pulverizacion\\Data\\CONTACTOS.xlsx'

In [13]:
sin_enviar = get_registros_sin_enviar()

In [14]:
cods_ca = list(set(sin_enviar['id']))
print(cods_ca)

[129, 643, 262, 395, 269, 399, 400, 529, 658, 659, 660, 664, 692, 413, 693, 419, 297, 299, 300, 303, 179, 180, 181, 438, 183, 439, 696, 698, 697, 691, 695, 694, 578, 579, 583, 200, 467, 471, 217, 474, 473, 350, 97, 353, 481, 356, 484, 483, 360, 233, 363, 364, 109, 366, 367, 493, 242, 243, 116, 626, 118]

In [15]:
len(cods_ca)

61

In [16]:
df_contac = pd.read_excel(PATH_XLSX_CONTAC)
df_contac.fillna(0, inplace=True)
df_contac = df_contac[['cod_ca', 'nom_ca', 'telf01', 'telf02', 'telf03']]

In [17]:
df_contac.head(3)

   cod_ca                 nom_ca    telf01      telf02      telf03
0   41529  ACUÑA CANO VICTORIANO  75540191         0.0         0.0
1   41594  AGROP. CAMPODULCE SRL  77166691  65004305.0  70804997.0
2     765   AGROP. CATALA S.R.L.  77396051         0.0         0.0

In [18]:
sin_enviar.head(3)

,id,fecha,institucion,cod_canero,nombre_canero,hectareas,cite,cod_propiedad,propiedad,producto,link,agrocittca,enviado
0,97,2025-09-24,8,1165,BEJARANO GANDARILLA ERWIN,11.03,CB-2025-90,40,SAN VICENTE--ERWIN BEJARANO,['TRICHOGRAMMA'],https://drive.google.com/file/d/1g8YpDinDp3gkD...,True,False
1,183,2025-10-15,304,1478,CALLE RALDEZ MARCO ANTONIO,3.53,CB-2025-176,1411,SAN JORGE--RENE CALLE,['TRICHOGRAMMA'],https://drive.google.com/file/d/1jh4DaMf1wyvzh...,True,False
2,217,2025-10-24,50,7506,LOHENER ROSENDA SHEILA PAZ DE,30.58,CB-2025-210,327,EL RECREO--ROSENDA SHEILA PAZ,['TRICHOGRAMMA'],https://drive.google.com/file/d/1I2alnKGfloK3k...,True,False

### Mensaje dirigiendo a agrocittca

In [19]:
for index, row in sin_enviar.iterrows():    
    contac_filtro = df_contac[df_contac['cod_ca']==row['cod_canero']]
    if not contac_filtro.empty:  # Verifica si hay al menos una fila
        contac = contac_filtro.iloc[0]
        telefonos = [int(contac['telf01']), int(contac['telf02']), int(contac['telf03'])]
        telefonos_validos = [telefono for telefono in telefonos if len(str(telefono)) == 8]
        if (len(telefonos_validos) == 0):
            print(f'❌ Codigo: {cod} no tinene numeros validos registrados')
            continue
        
        for num in telefonos_validos:
            msj = f'''🌱 *Saludos {row['nombre_canero']}*, le escribimos desde *UTEA - GUABIRÁ* para comunicarle que el informe del último servicio de *🐝 Control Biológico* realizado ya se encuentra disponible en *AgroCITTCA*.

📲 *Adjuntamos sus credenciales* para acceder a la App y los enlaces de descarga 👇

    👤 *Usuario:* {row['cod_canero']}
    🔑 *Contraseña:* 123*{row['cod_canero']}

⬇️ *Descargue la App:* 

📱 *Android:* https://play.google.com/store/apps/details?id=com.dima.guabira  

🍎 *iPhone:* https://apps.apple.com/us/app/agro-cittca-guabir%C3%A1/id1669149924

🚀 Una vez instalada la app, inicie sesión con su usuario y contraseña, y acceda a:  
📂 *AGROCITTCA → Seguimiento a campo → Informes*

Si tiene inconvenientes para acceder o visualizar los informes, no dude en consultarnos. ¡Gracias por su confianza! 🙌
'''         
            insertar_mensaje_whatsapp(
                cod_canero=row['cod_canero'],
                nombre_canero=row['nombre_canero'],
                numero_contac=f'591{num}@s.whatsapp.net',
                mensaje=msj
            )
            marcar_resumen_lib_enviado(row['id'])
    else:
        print(f"Codigo: {row['cod_canero']} - {row['nombre_canero']} no tiene registro telefonico")

Codigo: 1165 - BEJARANO GANDARILLA ERWIN no tiene registro telefonico
Codigo: 1478 - CALLE RALDEZ MARCO ANTONIO no tiene registro telefonico
Codigo: 7506 - LOHENER ROSENDA SHEILA PAZ DE no tiene registro telefonico
Codigo: 41562 - SUAREZ SALAS ERWIN RONALD no tiene registro telefonico
Codigo: 1182 - BOHORQUEZ FERNANDEZ NICANOR no tiene registro telefonico
Codigo: 2353 - CARO BENITES GERMAN no tiene registro telefonico
Codigo: 13638 - TISCO VASQUEZ SERGIO no tiene registro telefonico
Codigo: 1182 - BOHORQUEZ FERNANDEZ NICANOR no tiene registro telefonico
Codigo: 13638 - TISCO VASQUEZ SERGIO no tiene registro telefonico
Codigo: 2351 - CANDIA RUIZ ADALBERTO no tiene registro telefonico
Codigo: 2353 - CARO BENITES GERMAN no tiene registro telefonico
Codigo: 42378 - CANDIA RUIZ ORLANDO no tiene registro telefonico
Codigo: 1478 - CALLE RALDEZ MARCO ANTONIO no tiene registro telefonico
Codigo: 1165 - BEJARANO GANDARILLA ERWIN no tiene registro telefonico
Codigo: 42229 - CANDIA ROJAS JOSE LUIS no tiene registro telefonico
Codigo: 2619 - CANDIA RUIZ NESTOR A. no tiene registro telefonico
Codigo: 2351 - CANDIA RUIZ ADALBERTO no tiene registro telefonico
Codigo: 42229 - CANDIA ROJAS JOSE LUIS no tiene registro telefonico
Codigo: 42378 - CANDIA RUIZ ORLANDO no tiene registro telefonico
Codigo: 41562 - SUAREZ SALAS ERWIN RONALD no tiene registro telefonico
Codigo: 41562 - SUAREZ SALAS ERWIN RONALD no tiene registro telefonico
Codigo: 41562 - SUAREZ SALAS ERWIN RONALD no tiene registro telefonico
Codigo: 11231 - RAFAEL GARNICA FIDEL no tiene registro telefonico
Codigo: 42266 - GARCIA PETRONILA MARISCAL VDA. DE no tiene registro telefonico
Codigo: 42266 - GARCIA PETRONILA MARISCAL VDA. DE no tiene registro telefonico
Codigo: 4974 - GUTIERREZ GIL MARCIAL  no tiene registro telefonico
Codigo: 40253 - PAZ MELGAR RONY MAURICIO no tiene registro telefonico
Codigo: 2351 - CANDIA RUIZ ADALBERTO no tiene registro telefonico
Codigo: 7506 - LOHENER ROSENDA SHEILA PAZ DE no tiene registro telefonico
Codigo: 2619 - CANDIA RUIZ NESTOR A. no tiene registro telefonico
Codigo: 1165 - BEJARANO GANDARILLA ERWIN no tiene registro telefonico
Codigo: 42229 - CANDIA ROJAS JOSE LUIS no tiene registro telefonico
Codigo: 42378 - CANDIA RUIZ ORLANDO no tiene registro telefonico
Codigo: 13638 - TISCO VASQUEZ SERGIO no tiene registro telefonico
Codigo: 2353 - CARO BENITES GERMAN no tiene registro telefonico
Codigo: 41562 - SUAREZ SALAS ERWIN RONALD no tiene registro telefonico
Codigo: 1182 - BOHORQUEZ FERNANDEZ NICANOR no tiene registro telefonico
Codigo: 41562 - SUAREZ SALAS ERWIN RONALD no tiene registro telefonico
Codigo: 42266 - GARCIA PETRONILA MARISCAL VDA. DE no tiene registro telefonico
Codigo: 11231 - RAFAEL GARNICA FIDEL no tiene registro telefonico
Codigo: 7506 - LOHENER ROSENDA SHEILA PAZ DE no tiene registro telefonico
Codigo: 1478 - CALLE RALDEZ MARCO ANTONIO no tiene registro telefonico
Codigo: 42266 - GARCIA PETRONILA MARISCAL VDA. DE no tiene registro telefonico
Codigo: 2619 - CANDIA RUIZ NESTOR A. no tiene registro telefonico
Codigo: 13001 - SEJAS CASTRO EDWARDS no tiene registro telefonico
Codigo: 40253 - PAZ MELGAR RONY MAURICIO no tiene registro telefonico
Codigo: 4607 - GARCIA MARISCAL LEONCIO no tiene registro telefonico
Codigo: 42266 - GARCIA PETRONILA MARISCAL VDA. DE no tiene registro telefonico
Codigo: 11231 - RAFAEL GARNICA FIDEL no tiene registro telefonico
Mensaje insertado correctamente.
Mensaje con id=636 marcado como enviado.
Mensaje insertado correctamente.
Mensaje con id=645 marcado como enviado.
Mensaje insertado correctamente.
Mensaje con id=637 marcado como enviado.
Mensaje insertado correctamente.
Mensaje con id=637 marcado como enviado.
Mensaje insertado correctamente.
Mensaje con id=644 marcado como enviado.
Mensaje insertado correctamente.
Mensaje con id=644 marcado como enviado.
Mensaje insertado correctamente.
Mensaje con id=638 marcado como enviado.
Mensaje insertado correctamente.
Mensaje con id=642 marcado como enviado.
Mensaje insertado correctamente.
Mensaje con id=642 marcado como enviado.
Mensaje insertado correctamente.
Mensaje con id=642 marcado como enviado.
Mensaje insertado correctamente.
Mensaje con id=635 marcado como enviado.
Mensaje insertado correctamente.
Mensaje con id=639 marcado como enviado.
Mensaje insertado correctamente.
Mensaje con id=640 marcado como enviado.
Mensaje insertado correctamente.
Mensaje con id=641 marcado como enviado.

### Mensaje dirigiendo a PDF

In [19]:
for index, row in sin_enviar.iterrows():    
    contac_filtro = df_contac[df_contac['cod_ca']==row['cod_canero']]
    if not contac_filtro.empty:  # Verifica si hay al menos una fila
        contac = contac_filtro.iloc[0]
        telefonos = [int(contac['telf01']), int(contac['telf02']), int(contac['telf03'])]
        telefonos_validos = [telefono for telefono in telefonos if len(str(telefono)) == 8]
        if (len(telefonos_validos) == 0):
            print(f'Codigo: {cod} no tinene numeros validos registrados')
            continue
        
        for num in telefonos_validos:
            msj = f"Saludos *{row['nombre_canero']}*, le escribimos desde *UTEA - GUABIRA* para hacer llegar una copia del informe de servicio de control biologico en caña de azucar. También informale este informe lo puede encotrar en la aplicación AgroCITTCA, y que a partir de los proximos servicos los informes se enviaran direntamente a AgroCITTCA. Adjunto informe: {row['link']}"
            insertar_mensaje_whatsapp(
                cod_canero=row['cod_canero'],
                nombre_canero=row['nombre_canero'],
                numero_contac=f'591{num}@s.whatsapp.net',
                mensaje=msj
            )
            marcar_resumen_lib_enviado(row['id'])
    else:
        print(f"Codigo: {row['cod_canero']} - {row['nombre_canero']} no tiene registro telefonico")

Codigo: 1165 - BEJARANO GANDARILLA ERWIN no tiene registro telefonico
Codigo: 1478 - CALLE RALDEZ MARCO ANTONIO no tiene registro telefonico
Codigo: 7506 - LOHENER ROSENDA SHEILA PAZ DE no tiene registro telefonico
Codigo: 41562 - SUAREZ SALAS ERWIN RONALD no tiene registro telefonico
Codigo: 1182 - BOHORQUEZ FERNANDEZ NICANOR no tiene registro telefonico
Codigo: 2353 - CARO BENITES GERMAN no tiene registro telefonico
Codigo: 13638 - TISCO VASQUEZ SERGIO no tiene registro telefonico
Codigo: 1182 - BOHORQUEZ FERNANDEZ NICANOR no tiene registro telefonico
Codigo: 13638 - TISCO VASQUEZ SERGIO no tiene registro telefonico
Codigo: 2351 - CANDIA RUIZ ADALBERTO no tiene registro telefonico
Codigo: 2353 - CARO BENITES GERMAN no tiene registro telefonico
Codigo: 42378 - CANDIA RUIZ ORLANDO no tiene registro telefonico
Codigo: 1478 - CALLE RALDEZ MARCO ANTONIO no tiene registro telefonico
Codigo: 1165 - BEJARANO GANDARILLA ERWIN no tiene registro telefonico
Codigo: 42229 - CANDIA ROJAS JOSE LUIS no tiene registro telefonico
Codigo: 2619 - CANDIA RUIZ NESTOR A. no tiene registro telefonico
Codigo: 2351 - CANDIA RUIZ ADALBERTO no tiene registro telefonico
Codigo: 42229 - CANDIA ROJAS JOSE LUIS no tiene registro telefonico
Codigo: 42378 - CANDIA RUIZ ORLANDO no tiene registro telefonico
Codigo: 41562 - SUAREZ SALAS ERWIN RONALD no tiene registro telefonico
Codigo: 41562 - SUAREZ SALAS ERWIN RONALD no tiene registro telefonico
Codigo: 41562 - SUAREZ SALAS ERWIN RONALD no tiene registro telefonico
Codigo: 11231 - RAFAEL GARNICA FIDEL no tiene registro telefonico
Codigo: 42266 - GARCIA PETRONILA MARISCAL VDA. DE no tiene registro telefonico
Codigo: 42266 - GARCIA PETRONILA MARISCAL VDA. DE no tiene registro telefonico
Codigo: 4974 - GUTIERREZ GIL MARCIAL  no tiene registro telefonico
Codigo: 40253 - PAZ MELGAR RONY MAURICIO no tiene registro telefonico
Codigo: 2351 - CANDIA RUIZ ADALBERTO no tiene registro telefonico
Codigo: 7506 - LOHENER ROSENDA SHEILA PAZ DE no tiene registro telefonico
Codigo: 2619 - CANDIA RUIZ NESTOR A. no tiene registro telefonico
Codigo: 1165 - BEJARANO GANDARILLA ERWIN no tiene registro telefonico
Codigo: 42229 - CANDIA ROJAS JOSE LUIS no tiene registro telefonico
Codigo: 42378 - CANDIA RUIZ ORLANDO no tiene registro telefonico
Codigo: 13638 - TISCO VASQUEZ SERGIO no tiene registro telefonico
Codigo: 2353 - CARO BENITES GERMAN no tiene registro telefonico
Codigo: 41562 - SUAREZ SALAS ERWIN RONALD no tiene registro telefonico
Codigo: 1182 - BOHORQUEZ FERNANDEZ NICANOR no tiene registro telefonico
Codigo: 41562 - SUAREZ SALAS ERWIN RONALD no tiene registro telefonico
Codigo: 42266 - GARCIA PETRONILA MARISCAL VDA. DE no tiene registro telefonico
Codigo: 11231 - RAFAEL GARNICA FIDEL no tiene registro telefonico
Codigo: 7506 - LOHENER ROSENDA SHEILA PAZ DE no tiene registro telefonico
Codigo: 1478 - CALLE RALDEZ MARCO ANTONIO no tiene registro telefonico
Codigo: 42266 - GARCIA PETRONILA MARISCAL VDA. DE no tiene registro telefonico
Codigo: 2619 - CANDIA RUIZ NESTOR A. no tiene registro telefonico
Codigo: 13001 - SEJAS CASTRO EDWARDS no tiene registro telefonico
Codigo: 40253 - PAZ MELGAR RONY MAURICIO no tiene registro telefonico
Codigo: 4607 - GARCIA MARISCAL LEONCIO no tiene registro telefonico
Codigo: 42266 - GARCIA PETRONILA MARISCAL VDA. DE no tiene registro telefonico
Codigo: 11231 - RAFAEL GARNICA FIDEL no tiene registro telefonico
Codigo: 13001 - SEJAS CASTRO EDWARDS no tiene registro telefonico
Codigo: 40253 - PAZ MELGAR RONY MAURICIO no tiene registro telefonico
Codigo: 42266 - GARCIA PETRONILA MARISCAL VDA. DE no tiene registro telefonico
Codigo: 4607 - GARCIA MARISCAL LEONCIO no tiene registro telefonico
Mensaje insertado correctamente.
Mensaje con id=690 marcado como enviado.
Mensaje insertado correctamente.
Mensaje con id=690 marcado como enviado.
Mensaje insertado correctamente.
Mensaje con id=688 marcado como enviado.
Mensaje insertado correctamente.
Mensaje con id=687 marcado como enviado.
Mensaje insertado correctamente.
Mensaje con id=687 marcado como enviado.
Mensaje insertado correctamente.
Mensaje con id=689 marcado como enviado.