In [126]:
from datetime import datetime
import httpx

import cv2
import numpy as np
import requests
from pyzbar.pyzbar import decode

import pandas as pd

In [26]:
import sys
sys.path.append('..')
from sqlalchemy import create_engine, text
from sqlalchemy.dialects.postgresql import insert

from config import RUTA_UNIDAD_ONE_DRIVE
from config import RUTA_LOCAL_ONE_DRIVE
from config import API_AMIGOCLOUD_TOKEN_ADM
from config import POSTGRES_UTEA

In [27]:
def obtener_engine():
    return create_engine(
        f"postgresql+psycopg2://{POSTGRES_UTEA['USER']}:{POSTGRES_UTEA['PASSWORD']}@{POSTGRES_UTEA['HOST']}:{POSTGRES_UTEA['PORT']}/{POSTGRES_UTEA['DATABASE']}"
    )

In [74]:
def extraer_viajes_deltax(fecha_ini, fecha_fin):
    # 1. URL exacta para listar un intervalo de fechas según la imagen
    url = "https://api.production.scheduling.deltaxla.com/powerbi/guabira"
    
    # 2. Parámetros requeridos por esta API (start y end)
    params = {
        "start": fecha_ini,  # Ejemplo: "2023-07-25"
        "end": fecha_fin     # Ejemplo: "2023-07-26"
    }
    
    # 3. Token de autenticación obtenido de la documentación
    # NOTA: Asegúrate de copiar el texto completo de tu celda de Excel si aquí falta algún caracter
    TOKEN = "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6ImNiODBjZGI0LTQ5M2YtNGI0Ny04ZDc0LWE4YzNkYjZkODBiOCJ9.eyJzdWIiOiI2NDQ4OThjZDg2M2UyOGViZTA1YjczZTEiLCJpYXQiOjE2ODI0Nzk0OTB9.NS_nnd63YA93hgokINip8OqdZXbIXGv_8PUa8pL8GiMV29d_tKAe11GWLEgZ8UJJOSkCJsfV1XqTrm5aGSHbnQ" 
    
    headers = {
        "Authorization": f"Bearer {TOKEN}"
    }
    
    print(f"🔄 Conectando a API DeltaX...")
    print(f"📅 Rango solicitado: {fecha_ini} al {fecha_fin}")
    try:
        # Hacemos la petición con las cabeceras de seguridad y los parámetros de fecha
        with httpx.Client(timeout=15.0) as client:
            response = client.get(url, params=params, headers=headers)
            
            # Verificamos la respuesta
            if response.status_code == 200:
                print("✅ ¡Conexión exitosa a DeltaX!")
                return response.json()
            elif response.status_code == 401:
                print("❌ Error 401: No autorizado. Verifica que el BEARER TOKEN esté completo y vigente.")
                return None
            else:
                print(f"⚠️ Error en el servidor. Código de estado: {response.status_code}")
                return None
                
    except httpx.RequestError as e:
        print(f"❌ Error crítico de conexión: {e}")
        return None

def cambiar_tipo_dato(df_viajes_aux):
    viajes = df_viajes_aux.copy()
    # =====================================================================
    # 1. CONVERSIÓN DE TIPOS NUMÉRICOS (Enteros y Decimales)
    # =====================================================================
    # Columnas tipo INT (Enteros)
    columnas_int = ['gId', 'entryCode', 'caneOwnerCode', 'caneEstateCode', 'ticketNumber']
    for col in columnas_int:
        # errors='coerce' transforma valores corruptos o vacíos en NaN para evitar que el código falle
        viajes[col] = pd.to_numeric(viajes[col], errors='coerce').fillna(0).astype(int)
    # Columnas tipo DECIMAL / FLOAT (Decimales)
    columnas_decimal = ['scheduledLng', 'scheduledLat', 'unloadTn']
    for col in columnas_decimal:
        viajes[col] = pd.to_numeric(viajes[col], errors='coerce')
    # =====================================================================
    # 2. CONVERSIÓN DE FECHAS (Dates y Date Times)
    # =====================================================================
    # Columnas tipo DATE y DATE TIME (Pandas maneja ambos con datetime64)
    columnas_fechas = [
        'scheduledDate', 'estimatedArrivalDate', 'onRouteDate', 
        'scheduledDateTime', 'warehouseArrivalDate', 'processStartDate', 'finishedDate'
    ]
    for col in columnas_fechas:
        viajes[col] = pd.to_datetime(viajes[col], errors='coerce')
    # =====================================================================
    # 3. CONVERSIÓN DE TEXTO (Strings)
    # =====================================================================
    # Todas las demás columnas de texto
    columnas_string = [
        'id', 'caneOwnerName', 'scheduledBy', 'truckerName', 'plate', 'state', 
        'driverLicense', 'caneEstatePortionCode', 'shiftStartTime', 'shiftEndTime', 
        'preticketLink', 'unloadTicketLink', 'alcoholGrade'
    ]
    for col in columnas_string:
        viajes[col] = viajes[col].astype(str).replace('nan', '') # Limpia los nulos visuales de texto
    # =====================================================================
    # Verificación final
    # =====================================================================
    print("✅ Tipos de datos actualizados con éxito")
    return viajes

def cargar_datos_postgres(df, esquema_tabla="viajes_deltax"):
    """
    Carga un DataFrame a PostgreSQL. Si el 'id' ya existe, actualiza los datos.
    """
    # Creamos el motor de conexión
    engine = obtener_engine()
    
    # 2. Mapeamos los nombres de las columnas del DataFrame a minúsculas/snake_case
    # Esto es crucial para que coincidan exactamente con la tabla SQL que creamos antes
    mapeo_columnas = {
        'id': 'id',
        'gId': 'g_id',
        'entryCode': 'entry_code',
        'caneOwnerCode': 'cane_owner_code',
        'caneEstateCode': 'cane_estate_code',
        'ticketNumber': 'ticket_number',
        'caneOwnerName': 'cane_owner_name',
        'scheduledBy': 'scheduled_by',
        'truckerName': 'trucker_name',
        'plate': 'plate',
        'state': 'state',
        'driverLicense': 'driver_license',
        'caneEstatePortionCode': 'cane_estate_portion_code',
        'shiftStartTime': 'shift_start_time',
        'shiftEndTime': 'shift_end_time',
        'preticketLink': 'preticket_link',
        'unloadTicketLink': 'unload_ticket_link',
        'alcoholGrade': 'alcohol_grade',
        'scheduledLng': 'scheduled_lng',
        'scheduledLat': 'scheduled_lat',
        'unloadTn': 'unload_tn',
        'scheduledDate': 'scheduled_date',
        'estimatedArrivalDate': 'estimated_arrival_date',
        'onRouteDate': 'on_route_date',
        'scheduledDateTime': 'scheduled_date_time',
        'warehouseArrivalDate': 'warehouse_arrival_date',
        'processStartDate': 'process_start_date',
        'finishedDate': 'finished_date'
    }
    
    # Renombramos las columnas usando el mapeo
    df_sql = df.rename(columns=mapeo_columnas)
    
    # LE CORREGIMOS EL ORDEN: Forzamos el orden idéntico al del script SQL
    orden_columnas_sql = list(mapeo_columnas.values())
    df_sql = df_sql[orden_columnas_sql]  # <-- Esto garantiza que 'cane_owner_name' vaya en su sitio

    # 3. Definimos una función interna de soporte para SQLAlchemy que maneja el conflicto del ID
    def upsert_method(table, conn, keys, data_iter):
        # Convertimos los datos a diccionarios
        data = [dict(zip(keys, row)) for row in data_iter]
        
        # Creamos la sentencia de inserción de PostgreSQL
        insert_stmt = insert(table.table).values(data)
        
        # Indicamos qué columnas se deben actualizar si el 'id' entra en conflicto
        update_dict = {c.name: c for c in insert_stmt.excluded if c.name != 'id'}
        
        # Construimos el ON CONFLICT (id) DO UPDATE SET ...
        upsert_stmt = insert_stmt.on_conflict_do_update(
            index_elements=['id'], # Llave primaria que genera el conflicto
            set_=update_dict
        )
        
        # Ejecutamos en la base de datos
        conn.execute(upsert_stmt)

    # 4. Ejecutamos la carga masiva usando el método 'upsert_method'
    print(f"🔄 Iniciando la carga/actualización de {len(df_sql)} registros en PostgreSQL...")
    try:
        df_sql.to_sql(
            name=esquema_tabla,
            con=engine,
            if_exists='append', # 'append' es obligatorio para que funcione el método customizado
            index=False,
            method=upsert_method, # Aquí pasamos nuestra lógica de UPSERT
            schema='datos_iag'
        )
        print("✅ ¡Datos cargados y actualizados correctamente en PostgreSQL! ")
    except Exception as e:
        print(f"❌ Error al cargar los datos en la base de datos: {e}")

def procesar_ids_viajes(nombre_esquema="datos_iag"):
    """
    Ejecuta un script SQL para pasar los IDs de 'viajes_deltax' 
    a 'viajes_deltax_ids' omitiendo los que ya existan.
    """
    # 1. Configura tus credenciales de conexión
    engine = obtener_engine()
    # 2. Definimos el script SQL con la lógica de negocio
    # Usamos ON CONFLICT DO NOTHING para omitir los duplicados sin lanzar errores
    query_sql = f"""
    INSERT INTO {nombre_esquema}.viajes_deltax_ids (id_agendamiento, image_qr)
    SELECT id, preticket_link
    FROM {nombre_esquema}.viajes_deltax
    ON CONFLICT (id_agendamiento) DO NOTHING;
    """
    print("🔄 Ejecutando script de migración de IDs en PostgreSQL...")
    try:
        # 3. Abrimos la conexión y ejecutamos el comando dentro de una transacción segura
        with engine.begin() as conexion:
            resultado = conexion.execute(text(query_sql))
            # rowcount nos dice cuántas filas se insertaron realmente en esta ejecución
            print(f"✅ ¡Proceso completado! Se insertaron {resultado.rowcount} nuevos IDs únicos.")
    except Exception as e:
        print(f"❌ Error al ejecutar el script SQL: {e}")

In [64]:
# ==========================================
# EJEMPLO DE EJECUCIÓN
# ==========================================
if __name__ == "__main__":
    # Definimos el rango de fechas tal cual muestra el ejemplo de tu imagen
    fecha_inicio = "2025-11-19"
    fecha_fin = "2025-11-19"
    
    # Llamada a la función
    datos_viajes = extraer_viajes_deltax(fecha_inicio, fecha_fin)
    
    if datos_viajes:
        print("\n📊 Datos de viajes obtenidos:")

🔄 Conectando a API DeltaX...
📅 Rango solicitado: 2025-11-19 al 2025-11-19
✅ ¡Conexión exitosa a DeltaX!

📊 Datos de viajes obtenidos:

In [65]:
len(datos_viajes['freights'])

343

In [66]:
df_viajes = pd.DataFrame(datos_viajes['freights'])

In [67]:
df_viajes = cambiar_tipo_dato(df_viajes)

✅ Tipos de datos actualizados con éxito

In [112]:
cargar_datos_postgres(df_viajes)

🔄 Iniciando la carga/actualización de 343 registros en PostgreSQL...
✅ ¡Datos cargados y actualizados correctamente en PostgreSQL!

In [136]:
procesar_ids_viajes()

🔄 Ejecutando script de migración de IDs en PostgreSQL...
✅ ¡Proceso completado! Se insertaron 343 nuevos IDs únicos.

In [137]:
def obtener_viajes_sin_qr_df():
    """
    Busca los registros sin id_qr y los devuelve como un DataFrame de Pandas.
    """
    query = text("""
        SELECT * 
        FROM datos_iag.viajes_deltax_ids 
        WHERE id_qr IS NULL OR TRIM(id_qr) = '';
    """)
    engine = obtener_engine()
    with engine.connect() as conexion:
        df = pd.read_sql(query, conexion)
        
    return df

In [147]:
df_viajes_ids = obtener_viajes_sin_qr_df()

In [148]:
df_viajes_ids

Empty DataFrame
Columns: [id_agendamiento, id_qr, image_qr]
Index: []

In [140]:
def extraer_texto_qr(url):
    """Descarga la imagen y extrae el texto del código QR usando PyZbar."""
    try:
        respuesta = requests.get(url, timeout=10)
        if respuesta.status_code != 200:
            return None
        
        arr_imagen = np.frombuffer(respuesta.content, np.uint8)
        img = cv2.imdecode(arr_imagen, cv2.IMREAD_COLOR)
        
        if img is None:
            return None

        # --- AQUÍ CAMBIA LA LÓGICA ---
        # pyzbar analiza la imagen de forma mucho más robusta contra texto cercano
        codigos_encontrados = decode(img)
        
        if codigos_encontrados:
            # Extraemos el contenido del primer QR que encuentre y lo decodificamos a string
            valor_qr = codigos_encontrados[0].data.decode('utf-8')
            return valor_qr if valor_qr.strip() else None
        
        return None
        
    except Exception as e:
        print(f"Error al procesar la URL {url}: {e}")
        return None

In [141]:
def actualizar_id_qr_en_bd(df_procesado):
    """Actualiza la tabla viajes_deltax_ids en la base de datos con los QR extraídos."""
    # Filtramos solo los registros donde sí se logró extraer un QR con éxito
    df_validos = df_procesado[df_procesado['id_qr'].notna() & (df_procesado['id_qr'] != '')]
    
    if df_validos.empty:
        print("No hay registros válidos para actualizar en la base de datos.")
        return

    # Consulta optimizada para actualizar usando parámetros mapeados
    query = text("""
        UPDATE datos_iag.viajes_deltax_ids 
        SET id_qr = :id_qr 
        WHERE id_agendamiento = :id_agendamiento;
    """)
    
    # Preparamos los datos como una lista de diccionarios con las llaves que pide la query
    datos_actualizacion = df_validos[['id_qr', 'id_agendamiento']].to_dict(orient='records')
    
    engine = obtener_engine()
    try:
        with engine.begin() as conexion:  # .begin() maneja la transacción (Commit/Rollback) automáticamente
            conexion.execute(query, datos_actualizacion)
        print(f"¡Éxito! Se actualizaron {len(datos_actualizacion)} registros en PostgreSQL.")
    except Exception as e:
        print(f"Error al actualizar la base de datos: {e}")

In [142]:
# 1. Obtienes tu DataFrame actual con registros vacíos
df_viajes_sin_qr = obtener_viajes_sin_qr_df()
print(f"Iniciando la lectura de {len(df_viajes_sin_qr)} imágenes QR...")

Iniciando la lectura de 343 imágenes QR...

In [143]:
# 2. Aplicamos la función de extracción fila por fila a la columna 'image_qr'
# .apply() se encargará de recorrer las URLs y guardar el resultado en 'id_qr'
df_viajes_sin_qr['id_qr'] = df_viajes_sin_qr['image_qr'].apply(extraer_texto_qr)

In [144]:
df_viajes_sin_qr

,id_agendamiento,id_qr,image_qr
0,691d51c96b3b45b108c0988a,691d51ca6b3b45b108c0988c,https://dss-prod.s3.amazonaws.com/PreticketIng...
1,691d47176b3b45b108bf7964,691d47186b3b45b108bf7968,https://dss-prod.s3.amazonaws.com/PreticketIng...
2,691d440f6b3b45b108bf3149,691d44116b3b45b108bf314b,https://dss-prod.s3.amazonaws.com/PreticketIng...
3,691d44876b3b45b108bf3159,691d449e6b3b45b108bf315b,https://dss-prod.s3.amazonaws.com/PreticketIng...
4,691d46db6b3b45b108bf795f,691d46dd6b3b45b108bf7961,https://dss-prod.s3.amazonaws.com/PreticketIng...
...,...,...,...
338,691e13156b3b45b108d2b9e1,691e132d6b3b45b108d2fcaa,https://dss-prod.s3.amazonaws.com/PreticketIng...
339,691e2a896b3b45b108d5149b,691e2aa66b3b45b108d5149d,https://dss-prod.s3.amazonaws.com/PreticketIng...
340,691e33096b3b45b108d5ddcf,691e332c6b3b45b108d5ddd4,https://dss-prod.s3.amazonaws.com/PreticketIng...
341,691e60396b3b45b108da7255,691e60566b3b45b108da7257,https://dss-prod.s3.amazonaws.com/PreticketIng...
342,691e76d26b3b45b108dcb9fe,691e76f26b3b45b108dcba00,https://dss-prod.s3.amazonaws.com/PreticketIng...

In [145]:
# 3. Revisamos el progreso en el DataFrame
QRs_leidos = df_viajes_sin_qr['id_qr'].notna().sum()
print(f"Lectura terminada. Se lograron descifrar {QRs_leidos} de {len(df_viajes_sin_qr)} QRs.")

Lectura terminada. Se lograron descifrar 343 de 343 QRs.

In [146]:
# 4. Guardamos los cambios directamente en tu tabla de PostgreSQL
actualizar_id_qr_en_bd(df_viajes_sin_qr)

¡Éxito! Se actualizaron 343 registros en PostgreSQL.